### ISSUE TITLE
DefaultUser change in Pyramus

### ISSUE THREAD

**Issue by anttiviljakainen** [otavanopisto/muikku#1006]
Reproduction steps:
1. Have a Student in Pyramus which is synchronized to Muikku
2. Create a new studyprogramme for the student without updating the defaultuser i.e. let it point to the old studyprogramme.
3. Add the student to a course with the new studyprogramme, let it sync to Muikku
4. Change the default user to correct one (the new studyprogramme)
5. Log in to Muikku with the student and you do not see the course as your own course.

So in part 4 the synchronization should probably do some magic to fix this issue - or this may be related to the problem with old studyprogrammes not synchronizing to Muikku.

This can be fixed by triggering update for the coursestudent from Pyramus (f.ex. edit course, edit student on course and just save)

**Comment by anttiviljakainen** [comment]
Discussed with Mr.Leppä, maybe fixed with the old studyprogramme sync issue.

**Comment by pkukkon** [comment]
No longer reproducible in devel branch. Most likely fixed while fixing other bugs related to synchronizing workspace students.
