### ISSUE TITLE
Discussion message loading in production environment

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1038]
When discussion is loading different views, the loading animation won't show. It makes it feel like it's stuck.

**Comment by avukkonen** [comment]
This could be a part of a bigger story - a story of remade discussion. The current way of doing it does not recognize different states very well.

**Comment by ninakurki** [comment]
This may already be fixed, close if it is.

**Comment by onzag** [comment]
I don't seem to be able to reproduce, I believe it is fixed; please recheck.
