### ISSUE TITLE
"Broken records" (again)

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1101]
Picture says it all:

<img width="989" alt="screen shot 2015-12-14 at 08 16 38" src="https://cloud.githubusercontent.com/assets/3994573/11774173/1f317b74-a23b-11e5-9a42-5f5b45c47d08.png">

##### Details

 - Uses probably the wrong escape - HTML escaping in data attribute

**Comment by anttileppa** [comment]
Seems to be fixed
