### ISSUE TITLE
Paragraphs in communicator (discussion?) messages 

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1150]
> Onko niin, että muikku 3:n viestit eivät tee kappalejakoja. Kirjoitin viestin useaan eri kappaleeseen, painoin aina enteriä välillä. Viestin näkymä muuttuu, kun se tupsahtaa postilaatikkoon ja kas, kaikki onkin pötkönä. Onhan siinä tarvittavat asiat, mutta hieman kökköä kun eri asiat menee samaan putkeen. Onko tälle asialle tehtävissä mitään?

OsTicket ticket no. 275462 is waiting for this
Stakeholder Päivi Putkonen

**Comment by hkurhinen** [comment]
HTML was not rendered in communicator messages, possible fix in pull request #1284.
