### ISSUE TITLE
When enrolling in a workspace, notify the cost of evaluations

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#1197]
##### Details

 - The cost should be always visible to Internetix students and never visible to others

##### Stakeholders

 - Sari Jaaranen
 - Riitta Kesonen

**Comment by issakainen** [comment]
Didn't work. Used AT9 course and Anne Demo-Internetix user account. When requesting evaluation I did get a notification about the cost (ticket #1198)
