### ISSUE TITLE
Announcer - announcement creator unable to see his/her own announcements

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1278]
> Mikä kohderyhmä pitäisi valita, että opettajat, ohjaajat ja tällaiset administratoritkin pääsisivät näkemään tiedotteen? Jos jätän valitsematta, näkyy ehkä kaikille? Sellaiset tiedotteet nyt näkyvät (minulle), joissa ei ole kohderyhmää valittu.

User needs to be able to see his/her (created) announcements.

Stakeholder Miia Siven
Osticket ticket no. 645259

**Comment by anttiviljakainen** [comment]
Resolved in #2783 by giving roles permission to list group-assigned announcements.
