### ISSUE TITLE
Calendar - unable to browse months in datepicker (?)

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1299]
Miia Siven

> kuukausia ei pääse selaamaan, ainoa keino vaihtaa päättymispäivää on kirjoittaa se kuukausi kirjaimin, kalenterissa ei ole mitään selausmahdollisuutta.

**Comment by issakainen** [comment]
![nayttokuva 2016-04-20 kello 11 11 49](https://cloud.githubusercontent.com/assets/7565830/14667619/cf869592-06e8-11e6-8d27-6214c92bd7cb.png)

Missing the previous-next buttons

**Comment by pkukkon** [comment]
The month navigation buttons are actually there but not rendered correctly...
