### ISSUE TITLE
Remove lies from front page

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#1423]

**Comment by issakainen** [comment]
Muikku3 on Otavan Opiston kehittämä oppimisympäristö. Ympäristö tarjoaa kaikki tarvitsemasi työkalut opettamiseen ja oppimiseen:
	•	Avoimen lähdekoodin ympäristö
	•	Opiskelu onnistuu myös älypuhelimen tai tablet-laitteen kautta - ilman erillistä sovellusta.
	•	Koko näytön lukutila rauhoittaa opiskeluympäristön opiskelua varten.
	•	Yhdessä kirjoittamisen väline mahdollistaa ryhmätyöt ilman erillisiä ohjelmia.
	•	Pyramus -oppilaistoshallintajärjestelmän avulla voit hallitta opiskelelijoita ja kursseja
	•	Opettajien ja opiskelijoiden suunnittelma, ammattilaisten toteuttama

Tämä hyvä?

**Comment by anttileppa** [comment]
Mobiilituki ei ole valmis eikä meillä minun tietääkseni ole mitään yhteiskirjoitusvälinettä.

**Comment by pkukkon** [comment]
*Muikku 3 on...
*Pyramus-oppilaitoshallintajärjestelmän...
*...voit hallita opiskelijoita...
:P
