### ISSUE TITLE
Answering a muikku-message

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1448]
> Olen tässä viime päivinä tuskaillut seuraavaa, työtäni suuresti vaikeuttavaa asiaa
> 1. Kun saan sähköpostiini herätteenä oppilaan kommentin / viestin, joudun a)kirjautumaan itseni uuteen Muikkuun sisälle (salasanat menevät 'automaattisesti', mutta hitaahkosti), b)etsimään  oppilaiden viestit, c)avaamaan opiskelijan minulle lähettämän viestit ja vasta sitten d) vastaamaan siihen. Jokaisessa vaiheessa kuluu aikaa, jota ei ennen kulunut. = KÖMPELÖÄ ja HIDASTA.
> 
> Ennen samaan toimitukseen kuului vain a) paina sähköpostista vastaa <- nuolta ja kommunikoi oppilaan kanssa heti. 
> 1. Nykyisin tarvitsen tätä varten käytännössä tietokoneen, ennen sain vastailtua reaaliajassa tabletilla, puhelimella tai millä tahansa tietokoneella. Nyt saan etsiskellä tietokonetta ja häiriötöntä aikaa sekä suhteellisen nopeaa nettiä. 
> 
> Summa Summarum; Viestintä oppilaan kanssa on SUPERhankalaa verrattuna aikaisempaan. Missä on automaattivastaukset kurssi-ilmoittautumisiin? Miksi aina pitää kirjautua kömpelösti uuteen Muikkuun että hommat saa hoidettua? 
> 
> Nyt ollaan menty iso askel taaksepäin viestinnässä, vai enkö ole ymmärtänyt kaikkea?

**Comment by avukkonen** [comment]
Questions:

- Maybe answer a muikku-message with an email (like how with works with our ticket system)?
- Mobile version of muikku solves this partly? 
  - Can it be better integrated to an android system?

**Comment by issakainen** [comment]
Let's start working on this in two phases. First by provinding a direct link to the reason the notification email was send (direct message, assessment request, new student sign-up (link to the course)). Are there anything else?

On second phase we (maybe) start providing ticket system type of solution, but only if majority of teachers and students want it. We also need to check that there isn't any privacy law that forbids sending student data (grades...) directly to the students email.

**Comment by jjlankinen** [comment]
Closing this as stale issue.
