### ISSUE TITLE
Archiving student on study end

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1463]
> Nettiperuskoulun opiskelija Janina Pasanen sai opintonsa valmiiksi. Olen nyt arkistoinut hänet vanhaan tapaan vanhasta Muikusta sekä merkinnyt Pyramuksessa opinnot lopettaneeksi. 
> Löydän hänet edelleen uuden Muikun ohjaamosta haulla ja hänellä näyttää sen mukaan olevan vielä opinto-oikeutta. 
> Tarvitseekö minun tehdä vielä jotakin uuden Muikun puolella, jotta hänen tietonsa siellä arkistoituu?

Which then lead to this 

> Me keskustelimme silloin tiistaina tästä ja käsitin, että yleinen kanta oli, että kun opinnot merkataan päättyneeksi, niin silloin pitäisi myös Muikun sulkeutua kokonaan. Emme tässä kohtaa halua ns. alumneja mukaan, koska nykyisessä systeemissä sotkevat meidän käsitystä siitä, että kuka on oikeasti opiskelija ja kuka enää roikkuja. Laitan tämän myös Ninalle, Miialle ja Sarille, jotta en vain yksin olisi tämän takana.

Stakeholders: Annukka Manninen, Nina Kurki, Miia Siven, Sari Jaaranen
Osticket: 997112

**Comment by ilmoeuro** [comment]
Duplicate of #1463
