### ISSUE TITLE
workspace materials - answered / evaluated tasks

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1470]
As a user, I want to see the tasks I have done / that have been evaluated from the materials view.

Picked from facebook group "Muikkuverkko".

**Comment by avukkonen** [comment]
Two helpdesk tickets for this.

**Comment by jjlankinen** [comment]
Indicator should be added to TOC and assignment page

**Comment by issakainen** [comment]
Helpdesk Ticket #609395
