### ISSUE TITLE
Workspace material indentation unordered list

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1475]
> Saisiko sellaisen muutoksen, että jos luettelo alkaa sisennetyllä rivillä, sen merkki olisi sama kuin mikä se on normaalistikin luettelossa, kun riviä sisentää, eli valkoinen pallura.

![luettelomerkit](https://cloud.githubusercontent.com/assets/3994573/13005054/153da6f2-d188-11e5-98cc-43e61a893015.png)

Stakeholder: Saila Karjalainen 
osTicket: 349463

**Comment by jjlankinen** [comment]
Won't fix! Real issue is adding div element inside li elements and that is not working as intented.
