### ISSUE TITLE
Show "my own" students/workspaces in guider by default

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1497]
##### Source

Sari Jaaranen

>Kun menen Ohjaamoon, vasempaan reunaan listautuu pitkä lista ihan sekalaisia kursseja, joiden kanssa minulla ei oikeastaan ole mitään tekemistä. Siellä pitäisi näkyä minun julkaistut kurssit, joilla olen opettajana. 

>AT9 - Verkko-oppimisympäristön testaus( Kesäopiskelun 7-ottelu )
OP1 - HOPS-kurssi( Sarin ryhmä / Internetix 2016 )
OP1 - HOPS-kurssi( Sarin ryhmä 2016 )
OP1 - HOPS-kurssi( Sarin ryhmä / Internetix 2010 - 2015 )

OsTicket : 699568

##### Details

 - By default, show only the workspaces I'm a teacher in in the left pane
 - An additional "all students" option for managers and administrators
 - Maybe use the same logic as in coursepicker (?)

**Comment by ilmoeuro** [comment]
Administratorille näiden vissiin kuuluukin näkyä.

**Comment by issakainen** [comment]
This has been splitted in to a multiple different issues. The OsTicket owner has been also notifed.
