### ISSUE TITLE
Coursepicker - obsolete workspaces for student

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1500]
Sari Jaaranen says:

> Menin Muikkuun opiskelijatestitunnuksilla. Kurssipoimurissa on näkyvillä ihan ihmeellisiä kursseja, joiden ei pitäisi näkyä opiskelijoille.

>Biisinteko( Bändinlinja 2015-2016 )
Bändilinja - Yhteyesoitto I
Bändilinja 2015 - 2016
 Ja sitten esim. vanhoja ryhmiksiä kuten
GE1 - Sininen planeetta( ryhmäkurssi 7.12.2015-22.1.2016 )

osTicket: 927530

**Comment by ilmoeuro** [comment]
Kurssit on joku käynyt julkaisemassa, koodissa ei ole ongelmaa.

**Comment by ilmoeuro** [comment]
Asetetaan ainakin GE1-ryhmiksen näkyvyydeksi "vain jäsenille"
