### ISSUE TITLE
Communicator - autocomplete starts lagging more the longer the query param is

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1510]
Anna-Maria Suora:

>  Kun nyt yksitellen niitä vastaanottajien nimien näpyttelen siihen kenttään, niin näppikseni ikäänkuin lakkaa toimimasta tai tökkii. Olen nyt muutaman kerran tämän tehnyt ja tökkimistä tapahtuu vain tuossa vastaanottajakentässä eli vika ei varmaan olen näppiksessä. Eli samaa kirjainta tai välilyöntiä saa hakata muutaman kerran, että tulee yksi merkki. Yleensä ekat kolme kirjainta tulevat ihan OK.

osTicket: 335187

**Comment by issakainen** [comment]
Seems to be fixed
