### ISSUE TITLE
Guider - short course students are seen and we do not want to see them

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1536]
Hanna Riikka 

> Näköjään sinne listautuu nyt kaikki lyhytkurssin opiskelijat. Voisiko tuon ratkaista niin, että sinne listautuisi vain ne opiskelijat, joilla on opintojen aloituspäivämäärä. Kaikilla muilla linjoilla sellainen on. Lyhytkurssi-vapaalla kenelläkään ei ole opintojen aloituspäivämäärää.  

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=348

**Comment by issakainen** [comment]
Helpdesk email has been send, waiting for comfirmation
