### ISSUE TITLE
User name - only first name

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1537]
User says:

> Kyselisin vaan näinkin hölmöä kysymystä, että voisiko minun kohdallani tuolla muikun "Oma nimi" osiossa lukea vain etunimi ja sukunimi, eikä molempia nimiä, koska ne on niin samanlaiset. On vähän häiritsevää. Onko mahdollista muuttaa se?

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=346

This has also occured and been discussed before. Problem is, all names have been saved to "first name" field in Pyramus. ( == Could be also a pyramus issue).

**Comment by ninakurki** [comment]
@pkukkon Tämähän toimii kuin unelma eli voimme sulkea?
