### ISSUE TITLE
Eg. text is visible incorrectly after saving an exercise

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#1633]
Eg. text is visible after saving an exercise even when there is no example answers available.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=412

#### Stake Holder
Saila Karjalainen

**Comment by jjlankinen** [comment]
Repro: https://otavanopisto.muikkuverkko.fi/workspace/rub1-perhe-ja-lahiymparisto-2/materials#page-86356

**Comment by ilmoeuro** [comment]
The correctAnswers value for the corresponding WorkspaceMaterial was set as ALWAYS - probably the material type was changed and the value was left as-is. I'll fix the field in database if it's OK for others.
