### ISSUE TITLE
Workspace - editing front- and instructions page

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1656]
Kai Kaskela:

> etusivun ja ohjesivun muokkaus oli lisätty tonne hammasratasikonin taakse, noilta muokkaussivuilta puuttuu (edelleen) nappi millä pääsee takaisin kurssin työtilaan ilman että joutuu käyttämään selaimen backia.

osTicket: 957590

**Comment by avukkonen** [comment]
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=433

**Comment by ninakurki** [comment]
This has already been fixed.
