### ISSUE TITLE
User with "data transfer prohibition" cannot be seen in guider or in ToR

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1660]
Annukka Manninen reported that a student cannot be seen in guider. There are also other problems considering (at least) ToR - posibly more.

The student has a prohibiton for submitting his/her information forward, so I cannot quote the original report here.

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=417

**Comment by ilmoeuro** [comment]
This causes a lot of Pyramus GET-requests to fail for applicable students.
