### ISSUE TITLE
"You're not signed up into this course"-message link seems odd

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1676]
<img width="625" alt="screen shot 2016-03-14 at 08 30 47" src="https://cloud.githubusercontent.com/assets/3994573/13737649/88039ece-e9c7-11e5-94af-8fbb32dfd456.png">

**Comment by pkukkon** [comment]
Can no longer be reproduced; has been fixed in an earlier branch related to signing up to workspaces.
