### ISSUE TITLE
Search feature for messages in communicator

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#1706]
As a user I would like to search messages in communicator so it would be easier to respond to a specific student when there are several pages of messages.
#### Details
- Search by recipient, subject and maybe content
- Show the message threads (_not_ single messages) that match the search
#### OSTicket 803959

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=551
#### Stake Holder

Eeva Lehikoinen

**Comment by avukkonen** [comment]
##OsTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=663

**Comment by ninakurki** [comment]
Tämä on tehty.
