### ISSUE TITLE
Include signature for messages sent via communicator

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#1759]
As a user I would like to include signature to my messages sent via communicator.

#### Details

 - <strike>Signature is set in profile view</strike> Set signature in communicator settings

#### OSTicket 803959

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=551

#### Stake Holder

Eeva Lehikoinen

**Comment by anttiviljakainen** [comment]
Backend work started in FTR-1759-communicator-signature. Front end should probably still be groomed.

**Comment by avukkonen** [comment]
#2762
