### ISSUE TITLE
Evaluation assignment view's vertical scrolling won't activate properly

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#1782]
When user is using Windows 8.1 and latest Firefox browser, assignment's evaluation view won't activate vertical scrolling when moving mouse cursor on top of disabled textarea where students answer is. If cursor is moved to anywhere else in the same column other than disabled textarea vertical scrolling works as intended.

**Comment by issakainen** [comment]
Ticket #334244

**Comment by jjlankinen** [comment]
This should be fixed as students answers are not loaded as disabled textareas but instead they use readonly attribute. This should not prevent activation of scrolling anymore.
