### ISSUE TITLE
Archiving students on workspace evaluation

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1866]
Hanna-Riikka Karjalainen:

> Olisi hyvä, jos voisin arkistoida opiskelijat kurssilta myös tuolta arviointinäkymästä. Tämä vanha dementoitunut opettaja unohtaa näkymästä siirtyessään, ketä pitikään arkistoida. 

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=652
##### Details
- Wireframe for Miia
- After the teacher gives a passing grade to the student it in the workspace evaluation dialog a student archive confirm dialog opens with archive / don't archive buttons. 
- If teacher decides not to archive the student he/she can do it in the same workspace evaluation dialog.

**Comment by issakainen** [comment]
After the teacher gives a passing grade to the student it in the workspace evaluation dialog a student archive confirm dialog opens with archive / don't archive buttons.
If teacher decides not to archive the student he/she can do it in the same workspace evaluation dialog.
