### ISSUE TITLE
Protocol switches when attaching file to material

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#1875]
##### Source

> Moi
> Aiemmin liitetiedestoa paikalleen laittaessa protokolla vaihtui automaattisesti <muu>:ksi, kun liitetiedoston nimen vei osoitekenttään. Nyt siihen jää http, eikä sitä meinaa muistaa vaihtaa. Onko bugi, vai pitääkö opetella muistamaan?

##### Helpdesk reference

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=623

**Comment by pkukkon** [comment]
CKEditor functionality. Essentially works as intended.
