### ISSUE TITLE
Small UI bug fixes (Finnish)

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#188]
Lankisen kanssa pohdittua 24.10.2014

main-viewn pääelementit omiksi inserteikseen

main-viewn pääelementeille omat parametrit classeille

inserttien nimeäminen yhdenmukaistus (tarkentuva)

templaattien divit panelgroupeiksi (widgetit?)

widgetspacesetille oma divi (bugi)

ehdotus : faglet

Widgettien koot lasketaan kummallisesti

Widgetspacen pitää määrittä maksimikoko (varoitus, jos widgettikoko ylittää spacen maksimigridit)

Widgetspace jonka koko on 0 ei rendata?

Miten SUM, MINIMIZE ja MAXIMIZE toimivat? Siis oikeasti.

Widgetspacejen overflow-käsittely?

Widgettien maximi ja minimikoot — > alisteinen widgespacelle (Liian iso widgetti liian pieneen spaceen) ?

**Comment by issakainen** [comment]
Old issue. Please check if still valid.

**Comment by jjlankinen** [comment]
Not necessarily vakid anymore as we are shifting to different grid system in the future.
