### ISSUE TITLE
Hide archived student's diary entries

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#1901]
As a teacher I would like to hide archived student's diary entries from workspace diary view when Show all is selected.
##### OSTicket 262376

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=683
##### Stake Holder

Kai Kaskela
##### Details
- A checkbox-type selection in teacher's workspace journal view
- Affects both the entries shown in "show all" view and the students in the dropdown selection
- Archived students are color-coded/visually distinctive

**Comment by ninakurki** [comment]
@pkukkon Onkos tääkin duplikaatti siitä minkä korjasit? Jos on ni suljetaan.
