### ISSUE TITLE
File component instructional message

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#194]
File component instructional message (locale plugin.workspace.fileField.fieldHint) should have update support so that when the component enters read-only mode, the message either disappears completely (when a file has been uploaded and appears below it) or is replaced with "No file uploaded" (if not).

**Comment by issakainen** [comment]
Old issue, please check if still valid.

**Comment by jjlankinen** [comment]
Can't even find mentioned locale string nor I have no idea in what view this file field components message appeared.

**Comment by jjlankinen** [comment]
This locale string change needs to reviewed  at the same time as issue #987, way too complex to mortals this is.
