### ISSUE TITLE
Connection lost when re-submitting an assignment

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#1962]
Sometimes, when a student re-submits an assignment, Muikku displays the connection lost message. This does not happen every time but when it does, error notification "Assignment is already submitted thus can not be modified" is briefly shown, so it is likely related to the connection failing.

**Comment by avukkonen** [comment]
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=728#reply

**Comment by avukkonen** [comment]
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=726

**Comment by pkukkon** [comment]
Fix for #398 also fixed this.

**Comment by pkukkon** [comment]
Turns out fix for #398 was inadequate after all...
