### ISSUE TITLE
Image license, source and author punctuations are displayed incorrectly

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#1968]
Image license, source and author punctuations are displayed incorrectly when only 2 are set of those values.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=713

#### SH
Saila Karjalainen

**Comment by pkukkon** [comment]
If an image in a material has source, author, and license specified, the copyright text is correct:

"Source / Author, License"

If only source and license have been specified, the copyright text is incorrect:

"Source / License"
-> should be "Source, License"

If only source and author have been specified, the copyright text is incorrect:

"Source / Author,"
-> should be "Source / Author"

If only source has been specified, the copyright text is incorrect:

"Source /"
-> should be "Source"

If only author has been specified, the copyright text is incorrect:

"Author,"
-> should be "Author"
