### ISSUE TITLE
Evaluation view - text field task widths are too narrow

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1973]
Teacher Eeva Lehikoinen says:

> ena8-kurssilla (ja muillakin kursseilla) opiskelijan vastaukset aukkotehtäviin eivät näy kunnolla. Esim. Aapo Rytkönen ja tehtävät 6.5 Indefinite pronouns ja 7.6 Indefinite pronouns. Vastausta kun aikansa klikkailee, sen ehkä näkee kokonaan, mutta olisihan se hyvä nähdä heti koko vastaus. Mikä logiikka tässä mahtaa olla? :)

The textfield widths are 👎 
<img width="1327" alt="screen shot 2016-05-06 at 12 21 23" src="https://cloud.githubusercontent.com/assets/3994573/15069397/fad98f66-1385-11e6-8fcd-a16b9283af87.png">

**Comment by ninakurki** [comment]
Issue is already fixed.
