### ISSUE TITLE
Connect-field task type renders incorrectly

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#212]
See attached picture. Sets correctly if window resized. 
![nayttokuva 2015-05-21 kello 11 41 31](https://cloud.githubusercontent.com/assets/7565830/7744750/96fc0186-ffae-11e4-918f-29d7c047e368.png)

**Comment by pkukkon** [comment]
Not entirely sure about concurrency but this has been fixed by not refreshing the connect fields right after they have been rendered. Instead, they are all refreshed as the final task of the entire page initialization. This way the endpoint offsets seem to be calculated correctly.
