### ISSUE TITLE
Discussion: When loading more messages page should not scroll to top and refresh the whole list

### ISSUE THREAD

**Issue by petja-laitila** [otavanopisto/muikku#2176]
When loading more messages page should not scroll to top, it should wait for the messages where it is. Also it should add to existing threads, not load everything again.

**Comment by ninakurki** [comment]
This may already be fixed - close if it is.

**Comment by onzag** [comment]
It wasn't, a pull request has been attached.

**Comment by onzag** [comment]
PR on https://github.com/otavanopisto/muikku/pull/3122
