### ISSUE TITLE
Images are missing width and height values

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2205]
Some images in workspace materials are missing width and height values when editing them in editor. They seem to have width and height defined as inline styles instead of attributes.
#### OSTicket

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=836
#### SH

Saila Karjalainen

**Comment by ilmoeuro** [comment]
Won't fix: This is only a problem in legacy materials that have been imported using Deus Nex Machina.
