### ISSUE TITLE
Text sometimes goes behind TOC in materials

### ISSUE THREAD

**Issue by hkurhinen** [otavanopisto/muikku#2253]
Text sometimes goes behind TOC in material reading view. Example can be found from op1-mina-opiskelijana-3 in part 6.2

**Comment by avukkonen** [comment]
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=901

**Comment by avukkonen** [comment]
This was a mistake in the material: There was a table that was wider than the parent. I narrowed them down.
