### ISSUE TITLE
Link's target value does not work in discussion

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2324]
When creating new message in discussion user can add target value for links but it does not work.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1025

#### SH
Mia Siven

**Comment by avukkonen** [comment]
Needs to be whitelisted to work, but there's a security issue.

Read more:
  
http://davidebove.com/blog/2016/05/05/target_blank-the-vulnerability-in-your-browser/
