### ISSUE TITLE
Assignments and exercises broken if taskfields are copied

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2328]
If materials assignments are created by copy/paste taskfields inside ckeditor every copied taskfield has the same name and therefore after page reload every taskfield has same text.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=998

#### SH
Every student

**Comment by pkukkon** [comment]
FWIW, this only happens when copy/pasting multiple fields at the same time, in which case only the first field in the clipboard data gets a new, unique name.
