### ISSUE TITLE
Setting for limiting groups shown in workspace permissions view

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#2348]
Workspace permissions view currently lists practically all study programs and user groups. It should be possible to configure the view so that only "relevant" study programs and user groups would be listed.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1073

#### SH
Nina Kurki

**Comment by avukkonen** [comment]
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1073
