### ISSUE TITLE
File field with multiple files cuts connection

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2396]
When student somehow manage to upload more than 1 file to course's material's file fields browser loses connection to muikku and some times refuses to save the file field state.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1131

#### SH
Students

**Comment by pkukkon** [comment]
Duplicate of #2385. Since work on that one has not yet been started, closing it and considering this as the main issue.
