### ISSUE TITLE
Firefox loads workspace materials very slowly

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2427]
If workspace materials has .mp3 files (or iframes) firefox loads page very slowly if at all and prevents user to interact with materials in anyway while still loading.

When testing same workspace materials with chrome everything works nicely.

Net panel shows every .mp3 file regardless how small they are to slow down page load considerably  and sometimes browser stops loading them all together.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1139

#### SH
Every student

Workspace in question: https://otavanopisto.muikkuverkko.fi/workspace/ena5-kehittyva-kielitaito-tyoelamassa-toimiminen-ja-muita-muodollisia-tilanteita/materials

Repro: Remove Firefox cache or clean it before page load. Observe Net panel for .mp3 files

**Comment by pkukkon** [comment]
MP3 part of this issue should get fixed via #2437
