### ISSUE TITLE
Div element cannot be added inside list element

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2444]
When user adds div element inside list the style gets added to LI or UL in the worst case. 

It would be beneficial to be able to add div element inside another block level element instead of only wrapping UL or LI elements inside said div.

**Comment by ilmoeuro** [comment]
Only flow content is permitted inside LI: https://www.w3.org/TR/html-markup/li.html

DIV is not flow content

**Comment by jjlankinen** [comment]
This is working as intended. If user selects the text that is inside list item and then adds div element the div will be added to wrap the whole ol/ul element.

If instead user just selects the text inside li element and selects desired style via dropdown then selected text will be wrapper inside of div with proper styling added to it while still being nested to li element as intended.
