### ISSUE TITLE
TOC and assingment type, feedback

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#249]
TOC displays the assignment type by a colored bar. When the assignment has been submitted, the color should change to green (?) to give the pupil a quick view on what has been submitted and what now.

**Comment by jjlankinen** [comment]
I would propose that the border itself won't change color, instead we could use some background/shadow effect to indicate that state of the assignment/exercise.

**Comment by issakainen** [comment]
Good idea, let's work on that.

**Comment by issakainen** [comment]
Fixed
