### ISSUE TITLE
Resubmitted assignments need a visual clue in evaluation tool

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#253]
If users re-submits an assignment the teacher doesn't get a visual clue on this as after the teacher has submitted feedback the box visual clue goes to green.

**Comment by issakainen** [comment]
Now that evaluation tool has been revamped, is this still valid?

**Comment by jjlankinen** [comment]
If teacher has evaluated (read: submitted feedback) students assignment using non passing grade and student then withdraws his/hers assignment and re-submits it then corresponding assignment card in evaluation loses green borders and appears as if it's never evaluated. Maybe needs better indication for different states.
