### ISSUE TITLE
Discussion messages don't stay on course area

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#260]
Posts posted to course discussion area can also been seen on enviroment discussion area.

**Comment by jjlankinen** [comment]
This was meant to be like this but you should only see those messages if you have access to those messages via workspace. Messages written inside workspace should be placed into category named after that workspace. Should it work like that is debatable.

**Comment by jjlankinen** [comment]
This will be fixed as follows: We prevent messages written inside workspace to be seen at the enviroment discussion.

**Comment by issakainen** [comment]
Still an issue. See att. 
![nayttokuva 2015-10-08 kello 12 09 10](https://cloud.githubusercontent.com/assets/7565830/10362146/6b6fdf86-6db5-11e5-81cf-6ec3666d8900.png)
