### ISSUE TITLE
Multiple notification emails from muikku

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#2628]
It seems that muikku sends notification email from an event and after that from a muikku message that is a notification of it.

## Osticket

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1292
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1297
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1295

**Comment by pkukkon** [comment]
Also...

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1307

First e-mail: When a student signs up to a workspace or sends an evaluation request, a separate e-mail is sent to all teachers of the workspace (with a title that clearly indicates what the message is about).

Second e-mail: In addition, the same message is added to the Muikku communicator. Whenever a new communicator message is created, the recipient gets an e-mail about it (with a title that states there's a new message in Muikku).

Questions for grooming:

Should a separate e-mail be sent at all?
Should a communicator message be added at all?
If only one e-mail is preferred, which caption should it have?

Possible fixes:

1) Don't send first e-mail
+ user only gets one e-mail
- the e-mail has a generic title "New message in Muikku"

2) Don't add a communicator message
+ user only gets one e-mail
+ the e-mail has a descriptive title
- there would be no communicator message

3) Send first e-mail, add communicator message but skip the second e-mail
+ user only gets one e-mail
+ the e-mail has a descriptive title
+ the information is stored in communicator (needed?)
- misleading that some communicator messages cause notifications and others do not?

4) "Works as intended"
- user gets two e-mails

**Comment by ilmoeuro** [comment]
Chosen alternative #3
