### ISSUE TITLE
Separate "my curriculum" credits from other credits in ToR

### ISSUE THREAD

**Issue by anttiviljakainen** [otavanopisto/muikku#2648]
If student that has a set curriculum completes a course with different curriculum he/she cannot view the assessment anywhere because the ToR only lists assessments for the curriculum of the student.

So, should the ToR list the other assessments/credits too, should they be accessible from inside the course or something else?

**Comment by pkukkon** [comment]
At least it would feel natural for ToR to contain everything relevant to the student's studies. If that is a problem, maybe different views and/or filters could be used? Something like "Show only records of my current curriculum" and "Show all my records."

Assessments shown inside the workspace is not feasible, as students are currently often archived from the workspace after they have been evaluated, so they end up losing access to the workspace altogether.

**Comment by ilmoeuro** [comment]
Ask more information about this from Miia

**Comment by anttiviljakainen** [comment]
Categorize the credits in ToR by their curriculum so that if student has default curriculum those are always shown first but so that it is always possible to view all the credits anyways.
