### ISSUE TITLE
Versioned pages in materials

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#2665]
As a material producer, I want to be able to produce a new version of a material page, so that I can edit exercises with answers.

#### Details

 - When a student enrolls to a course, they *always* see the version of the material page that was when they enrolled
 - When evaluating the student, evaluate *that* version
 - If new materials are created after a student enrolls, the student will see the *first* version of that material
 - If there's no exercises done, and the student re-enrolls at the course, the version is determined by the *latest* enrollment
 - Material producers should be able to browse and edit all versions of the material
 - Material versions with no answers should be deletable (works like deleting material pages)
 - Metadata (author, title, license, visibility etc) is per version
 - Copy only the latest version when copying the course
 - When creating a new version, the new version is empty

**Comment by jjlankinen** [comment]
Closing this as stale issue.
