### ISSUE TITLE
CourseStudent update from Pyramus doesn't update studyprogramme changes properly

### ISSUE THREAD

**Issue by anttiviljakainen** [otavanopisto/muikku#268]
CourseStudent update from Pyramus doesn't update studyprogramme changes properly.

Reproduce:
1. Have student in Pyramus who has at least two studyprogrammes
2. Put the student on a course
3. After it has been synchronized to Muikku, change the studyprogramme for student on the course in Pyramus
4. The Student reference (userschooldataidentifier) in workspaceuserentity should still refer to the old studyprogramme while it should update to the new one

**Comment by anttileppa** [comment]
Fixed as a part of another story
