### ISSUE TITLE
New evaluation's evaluate button won't work in iPhone 6S

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2698]
When using new evaluation with mobile devices (iPhone 6s) evaluate button inside request cards won't do anything.

**Comment by ilmoeuro** [comment]
Works in Android 7.1

**Comment by pkukkon** [comment]
Works on iPhone 6S, at least with iOS 10.2 #beta6

**Comment by pkukkon** [comment]
http://stackoverflow.com/questions/3705937/document-click-not-working-correctly-on-iphone-jquery

Most certainly will not refactor tons of code to replace all document-based click handlers just because Apple disagrees with everyone else.
