### ISSUE TITLE
CKEditor's dialogs occasionally disabled

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2777]
Sometime in evaluation and material editing CKeditor's dialogs won't activate properly and instead stays disabled (not disabled by disabled attribute) ie. form elements cannot be interact with.

It has happened in windows 8, 8.1 and 10 using Chrome and Firefox.

**Comment by jjlankinen** [comment]
Cannot reproduce this bug. Maybe some browser addon affecs form field focuses or something.

Possible problem occurs when using JQuery dialogs to show CKEditor but that's not the case hare.

**Comment by avukkonen** [comment]
Cannot reproduce.
