### ISSUE TITLE
Connect field cannot be scrolled with touch devices

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2792]
When using touch devices its impossible to scroll page if connect field assignment is in users view port. Right side's drag and drop events overrides touch scrolling.

#### Details

 - Don't start working on this until #3093 is completed

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1393

#### SH
Every touch screen user

**Comment by onzag** [comment]
Isn't this the same issue that the users got to report now?... should I get it done based on this one.

**Comment by onzag** [comment]
@jjlankinen are you sure draggables didn't work before, it is actually not possible to solve some maaterialit without the dragabble functionality as it is now, also sortables do work in my android phone, somehow; https://demo.muikkuverkko.fi/workspace/bi4-ihmisen-biologia/materials check it out.
