### ISSUE TITLE
Dropdown (quiztype), unable to delete the first choice

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#282]
Even if the dropdown has several other choices below the first one you are unable to delete the first unless you first drag it down after which the trashcan icon appears. 

If there is more choices than one then the first choice should be able to delete. 
![nayttokuva 2015-06-10 kello 12 29 09](https://cloud.githubusercontent.com/assets/7565830/8079335/6e923b7a-0f6c-11e5-97a7-3c603e33159d.png)
![nayttokuva 2015-06-10 kello 12 29 17](https://cloud.githubusercontent.com/assets/7565830/8079339/74e46944-0f6c-11e5-8797-34c288f62a54.png)

**Comment by pkukkon** [comment]
Fixed by simply displaying the delete icon for the first option as well.
