### ISSUE TITLE
Teachers unable to access to unpublished courses

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#284]
Teachers should see their own unpublished courses on course picker so that they can access them without the need to publish them / navigate directly to url.

Administrator should see ALL unpublished courses on course picker.

**Comment by issakainen** [comment]
Setting up priority label to this.

**Comment by jjlankinen** [comment]
Added Teachers selection to coursepicker dropdown and visual indication to that list ti indentify if workspace is not published.
