### ISSUE TITLE
Evaluating assignment prevents students to resubmit assignment

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2841]
When student submits assignment and teacher evaluates it as incomplete, student cannot withdraw the assignment as system thinks it's evaluated as failed/passed. There is no middle ground to incomplete check and therefore prevents students to fix issues with his/hers assignment.

#### Details
 - Will be solved by #2291

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1426#note

#### SH
Taina Portman

**Comment by ilmoeuro** [comment]
Archived because #2930 solves this problem.
