### ISSUE TITLE
"Outside guider" role

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#2845]
Add an outside guider role that has limited access to only specific students

#### Details

 - Show only the guider view
 - Can only see the students of the groups that the guider is staffed in
 - Linked to otavanopisto/pyramus#441
 - Doesn't need communicator, guider etc

#### Stakeholder

Annukka Manninen

**Comment by anttiviljakainen** [comment]
* pystyy hakemaan omia opiskelijoitaan (ei muita)
* pystyy tarkastelemaan juurikin ohjaamossa opiskelijan etenemistä (ei pääse muiden opiskelijoiden tietoihin)
* pääsee nille kursseille katsomaan materiaalia ja tehtäviä, joilla opiskelija on (tämä nyt onnistuu käytännössä ilman kirjautumistakin)
* pystyy laittamaan viestiä Muikun kautta omille ohjattavilleen 
* tarvittaessa pystyy olemaan oma ns "kotipesäkurssi" omille opiskelijoille
