### ISSUE TITLE
Guider - A teacher with permission problems with flagging

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#2859]
Laura Luoma:

>Tein eilen liputuksen yhden opiskelijan kohdalle (Gina Jokinen) ja tänään yritin jakaa lippuani Ginan ohjaajalle. En kuitenkaan pääse tekemään lipulleni missään valikossa muuta kuin "muokkaa" tai "poista". Muikku avaa kuusi "forbidden" -ikkunaa eteeni.

Rest gives 403 accordingly

## Osticket

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1443

**Comment by anttiviljakainen** [comment]
Teacher has no permission to forumStatistics for certain workspace and student.
