### ISSUE TITLE
Unable to submit assignments when using Microsoft Edge

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2865]
When using microsoft edge browser user is unable to submit assignments or check exercises.

When pressing submit button nothing happens. Cannot reproduce using VM.

When said user tried android phone everything worked fine.

Latests update to windows for this user is: Kumulatives Update für Windows 10 Version 1607 für x64-basierte Systeme (KB3213986)

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1441

#### SH
Teija Spiekien

**Comment by ninakurki** [comment]
Unable to be repeated with WIN10 and Edge.
