### ISSUE TITLE
Workspaces - bug with student that has ended studies and started again

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#2917]
Workspace sign ups that were done before studies ended the last time are shown after the studies started again. This isn't a prolem by itself, but the workspaces don't recognize the user as signed up. 

There are two options to solve the issue:

1. Remove the past study workspaces from the users workspaces
2. Make the workspaces recognize the user as signed up so they can either continue studying in it or the teacher can remove them from the workspace.

## Osticket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1480

Duplicate of #3044

**Comment by anttiviljakainen** [comment]
Closed as fixed. Students are archived from courses when they end their studies and they can reapply to the course if they start their studies again. They can also be reinstated from the course user management and their answers to the exercises remain between studies.
