### ISSUE TITLE
Teacher should only see his/her own workspaces' details in student profile

### ISSUE THREAD

**Issue by anttiviljakainen** [otavanopisto/muikku#2926]
In student profile a teacher should only see details on workspaces that the teacher is teacher on and only the basic information for all other workspaces (for the student).

**Comment by ninakurki** [comment]
Suljetaan, koska:
Opettaja ei tarvitse tietoa muusta opiskelijan kurssisuoritus- tai arvosanahistoriasta, vaikka varmaan joissain tapauksissa se kiinnostavaa olisikin. Kiinnostus ei kuitenkaan riitä perusteeksi, eikä muilla kursseilla suoriutumisen tulisi vaikuttaa esim. opettajan kurssillaan tekemään arviointiin.
