### ISSUE TITLE
Problems with attachment

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#302]
Loaded attachment, embedded it and tried to change the visibility status of the document in which embedded. Getting following errors: 

    http://otavanopisto.muikkuverkko.fi/workspace/ena6-tyo-ja-opiskelu_2/materials/1.-lets-get-going-0/start.jpg Failed to load resource: the server responded with a status of 404 (Not Found)

    jquery.js:8625 PUT http://otavanopisto.muikkuverkko.fi/rest/workspace/workspaces/927/materials/10882/ 500 (Internal Server Error)

Relevant stack trace:

    Caused by: javax.validation.ConstraintViolationException: Validation failed for classes fi.muikku.plugins.workspace.model.WorkspaceMaterial] during update time for groups [javax.validation.groups.Default, ]
    List of constraint violations:[ConstraintViolationImpl{interpolatedMessage='may not be null', propertyPath=title, rootBeanClass=class fi.muikku.plugins.workspace.model.WorkspaceMaterial, messageTemplate='{javax.validation.constraints.NotNull.message}' ConstraintViolationImpl{interpolatedMessage='may not be empty', propertyPath=title, rootBeanClass=class fi.muikku.plugins.workspace.model.WorkspaceMaterial, messageTemplate='{org.hibernate.validator.constraints.NotEmpty.message}'} ]

**Comment by pkukkon** [comment]
The attachment URL is incorrect. When a document title is modified, its URL name changes as well, which in turn affects the URL of the attachment. In other words, whenever the document title is changed, attachments should be embedded again. This is extremely awkward but won't be fixed until we have a proper CKEditor plugin to handle document attachments.

**Comment by pkukkon** [comment]
Fixed in another issue.
