### ISSUE TITLE
Frontpage - last courses 

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#3043]
Last courses show only older courses.  There are subtopics missing.

**Comment by ninakurki** [comment]
Is this the same one we already fixed or is this something else? Perhaps we can check this one and close the issue if it is already fixed.

**Comment by onzag** [comment]
@ninakurki depends, ovatko nuo workspaces? tuo on fixed. @avukkonen missä bug on? mikä screen?

**Comment by onzag** [comment]
Yes it's #3098
