### ISSUE TITLE
Courses in past study programme are showing in the front page as active

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#3044]
Teacher Petra Roininen says: 

>NN  erosi syksyllä nettilukiosta ja tuli nyt takaisin. Hän kertoo, että hänellä näkyvät myös nämä "vanhat" kurssit, millä oli mukana viime vuoden puolella. Kurssi ilmoittaa, että ei ole sillä mukana, mutta silti kuulemma näkyy... Minä en näe Ohjaamosta kuin nämä uudet, mutta saatteko tehtyä näille " vanhoille" kursseille siellä jotain? 

This indeed is the case. There are past study programme courses showing, but user is not able to study in them.

**Comment by anttiviljakainen** [comment]
Closed as fixed. Students are archived from courses when they end their studies and they can reapply to the course if they start their studies again. They can also be reinstated from the course user management and their answers to the exercises remain between studies.
