### ISSUE TITLE
Assessing a student may function improperly

### ISSUE THREAD

**Issue by anttiviljakainen** [otavanopisto/muikku#306]
As reported: Sometimes, when you assess a student the assessment disappears (after save you are left with empty inputs). However, the assessment may have been saved despite. The empty boxes suggest that the save failed and you need to do it again which in turn may lead to duplicate assessments.

**Comment by anttiviljakainen** [comment]
Confirmed, after assessment the assessment doesn't show in Muikku even tho it is saved in Pyramus.

**Comment by pkukkon** [comment]
A-yup. The assessment was created but the callback method simply closed the evaluation dialog without ever bothering to store the returned evaluation to the view. In other words, from the user perspective nothing happened. Fixed by storing the created evaluation properly.
