### ISSUE TITLE
CKeditor draft support might not work properly

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#3067]
There has been incident where ckeditor's draft has not been working as intended in evaluation.

Teacher reported that after session timeout and page reload editor did not offer to restore previous version of said evaluation.

#### OSticket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1608

#### SH
Anne Rongas

**Comment by anttiviljakainen** [comment]
Cannot reproduce. Possibly used two browsers or localstorage-incompatible browser.
