### ISSUE TITLE
Check if course fee logic is correct

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#3069]

**Comment by pkukkon** [comment]
Fee logic has now been adjusted as follows:

Evaluation fees are applicable to all Internetix students.

If the student has any school set in Pyramus, every workspace has an evaluation fee.

If the student does not have a school specified, the workspace has an evaluation fee if its suitability does not include lukio/pakollinen, lukio/valtakunnallinen syventävä, peruskoulu/pakollinen, or peruskoulu/valinnainen.
