### ISSUE TITLE
Text changes to "HOPS-lomake"

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#3096]
Some text changes and more to "HOPS-lomake" as described below.

HENKILÖKOHTAINEN OPISKELUSUUNNITELMA (HOPS)

**** ALUN TEKSTI ****

[KORVATAAN KOKO ALUN TEKSTI ALLA OLEVALLA TEKSTILLÄ]

[BOLD]
Tämä lomake auttaa sinua henkilökohtaisen opiskelusuunnitelman (HOPS) laatimisessa. Vastaa kysymyksiin tämän hetkisten ajatustesi pohjalta, voit muuttaa suunnitelmaasi myöhemmin. HOPS on ensijaisesti sopimus itsesi kanssa: mitä, miten ja milloin aiot opiskella. Jos täytät lomakkeen itsenäisesti, tutustu huolellisesti täyttöohjeisiin.

Palauta HOPS omalle ohjaajallesi tallentamalla lomakkeen tiedon näkymän alareunan Tallenna-painikkeesta.
[/BOLD]

Lukio-opintoihin saat opiskeluaikaa enintään neljä vuotta. Voit suorittaa opinnot noin 2-4 vuoden aikana riippuen opinto-oikeutesi kestosta ja ajankäytöstäsi. Aiemmat lukio-opinnot vähentävät sinulle myönnettyä opiskeluaikaa.

Vähintään 2,5-vuotinen ammatillinen perustutkinto (120 ov / 180 osp) antaa suoraan osallistumisoikeuden yo-kirjoituksiin. 2-vuotisen ammatillisen tutkinnon suorittaneelta vaaditaan vähintään kahden <B>pakollisen</B> lukiokurssin suorittamista niissä oppiaineissa, joiden yo-kokeisiin hän haluaa osallistua.

**** LOMAKE-OSUUS ****

Minulla on X vuoden [POISTA: tai vuosien] laajuinen ammatillinen perustutkinto ja haluan suorittaa pelkät yo-kirjoitukset

[AMMATILLISEN TUTKINNON LAAJUUDESSA PITÄISI OLLA VAIHTOEHTONA MYÖS: 2,5]

Arvioin suorittavani lukion x vuodessa -kohdasta POIS TEKSTI:
(HUOM! Aiemmat lukio-opinnot vaikuttavat opiskeluaikaan).

Haluan suorittaa seuraavat pakolliset kielet -tekstin TILALLE:
Äidinkielessä ja kirjallisuudessa voit valita suomi toisena kielenä -oppimäärän, jos äidinkielesi on jokin muu kuin suomi. Suoritan äidinkielessä oppimäärän

[ÄIKKÄ-KOHDAN JÄLKEEN ENNEN VALINNAISIA KIELIÄ]:
Äidinkielen lisäksi aikuislukiolaiset opiskelevat pakollisena A-englantia ja B-ruotsia.

[AINEET JÄRJESTELLÄÄN PERIAATTEELLA äidinkieli, B1-kieli, A-kieli, B3-kieli, matematiikka, luonnontieteet, katsomusaine ELI KÄYTÄNNÖSSÄ KIELET EKA JA MATIKKA TOKA]

SIIS NÄIN:
Haluan suorittaa seuraavat pakolliset kielet [TÄHÄN TULEE SIIS UUSI TEKSTI]
Haluan suorittaa valinnaiset kielet
Matematiikan opiskelu alkaa...
Luonnontieteissä....
Katsomusaineeni on...

[ENNEN TALLENNA-PAINIKETTA] Lisätietoa-kenttä

**Comment by pkukkon** [comment]
Implemented as part of #2941

**Comment by ninakurki** [comment]
@pkukkon Voisiko tämän jo sulkea?
