### ISSUE TITLE
Signing up to a workspace that you have completed

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#3097]
Taina Portman:

> Opiskelija ilmoittautui kurssille, teki tehtävät ja arvioin kurssin sekä arkistoin opiskelijan. Sitten hän sai jostain päähänsä (kuulemma Muikussa välähti nopeasti joku viesti sisäänkirjautuessa), että ei ollut ilmoittautunut kurssille oikein, ja päätti ilmoittautua uudelleen tälle kurssille ja lähettää heti uuden arviointipyynnön.

So we need to decide to either block users from signing up to workspaces they have already completed or make it available for teachers to scrap evaluation requests -at least when the case is there already is an evaluation. 

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1661

**Comment by jjlankinen** [comment]
Students cannot sign up to a course they have completed successfully or failed it anymore. This has been fixed in another issue: #4700
