### ISSUE TITLE
Evaluation dialog hides notification queue

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#310]
When saving an evaluation, all messages posted in the application's notification queue appear behind the evaluation dialog. Some sort of z-index problem?

**Comment by issakainen** [comment]
Now that evaluation tool has been revamped, is this still valid?

**Comment by jjlankinen** [comment]
Notification queue's z-index has been raised to a magnificent level (99999) so this should be an issue anymore.
