### ISSUE TITLE
Communicator's Settings view does not open when reading a message

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#3123]
If you click a message in Communicator to read it, and then click the Settings icon on the top-right, the Settings view does not display. Works normally when opening it from the front page of the Communicator.

**Comment by onzag** [comment]
Pull request at https://github.com/otavanopisto/muikku/pull/3138

**Comment by ninakurki** [comment]
Is there a reason why this is still here? Is this one already done or not reviewed? @onzag @ilmoeuro
