### ISSUE TITLE
Course Discussion: Load more messages -button does not work

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#3173]
Heli Viitanen wrote via helpdesk:

> https://otavanopisto.muikkuverkko.fi/workspace/ena6-tiede,-talous-ja-tekniikk_1/discussions#a131/591
> 
> Kyseessä ENA6-kurssin keskustelualue ja oma viestiketjuni, jossa on 38 kommenttia. En pääse lukemaan kuin vanhimmat. Mitään ei tapahdu, kun klikkaan Lataa lisää viestejä. Jos klikkaan sitä uudestaan, koko Lataa lisää viestejä -palkki häviää. Näytössä käväisee Odotetaan palvelinta.
> 
> Tämä on toiminut aiemmin muttei nyt ainakaan muutamaan päivään. En siis pääse nyt lukemaan opiskelijoiden tehtävien tätä osaa. 
> 
> Heli

Load more messages -button does not work. This problem is in the course discussion.

**Comment by onzag** [comment]
I can't replicate, se on toissa chrome ja firefox, any specific selain?

**Comment by ninakurki** [comment]
I tried this with Chrome and the ENA6-course Heli Viitanen reported the problem is. Load more -button does not work there. I tried to find another course where is enough messages to test this but I couldn't find any.

I also noticed that we have to be specific about what discussion we are talkin about! This problem is in the Course Discussion. It seems that in the general discussion there is still that problem what was described in issue #3122.
