### ISSUE TITLE
Workspace evaluation request - can be send multiple times

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#3178]
Saila Karjalainen says:

> Käyn Anne Demona juttuja läpi, kun päivitän opiskelijoiden ohjeita. Anne Demo on arvioitu esim. AT9-kurssilta hyväksytysti, mutta se pystyy laittamaan uuden arviointipyynnön. Onko tarkoituksella näin, siis sekä tuo toiminto että näkymä?

**Comment by avukkonen** [comment]
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1705

**Comment by jjlankinen** [comment]
Suljetaan koska toimii kuten pitääkin, uuden arviointipyynnön esto on olemassa vasta kun opiskelija on arkistoitu kurssilta (tällöinkin vain siten että uudelleen ilmoittautuminen arvioidulle kurssille on estetty) ja tämä tapahtuu usein vasta 2 viikkoa hyväksytyn arvioinnin jälkeen jotta opiskelijalla on mahdollisuus korottaa arvosanaa.
