### ISSUE TITLE
Communicator - item loading is slow 

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#3179]
From new relic: 

<img width="420" alt="screen shot 2017-05-22 at 14 04 05" src="https://cloud.githubusercontent.com/assets/3994573/26305388/b9cb5fec-3ef7-11e7-9457-1b9a295e54ed.png">

**Comment by petja-laitila** [comment]
Additional info from new relic. It's mysql query that is taking that time:
Database	MySQL communicatormessagerecipient select 3,100ms
