### ISSUE TITLE
Using angle brackets inside assignments textarea gets interpred as html tags

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#3212]
If student puts link inside angle brackets in textarea when anwering to assignment ie. <http://www.link.com/> muikku handles it as html tag and it does not render properly for teachers in evaluation view.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1759

#### SH
Johanna Mattila

**Comment by avukkonen** [comment]
This is a common ckeditor issue:

> 
> The only workaround I've found so far is to use
> 
> CKEDITOR.instances.myInst.setData(myData);
> This actually handles escaped vs. unescaped html correctly, so your < and > will come out correctly, as less-than and greater-than signs, instead of being interpreted as markup.
> 
> I haven't found a way to get this to work with inlined data yet. The setData() workaround is pretty clunky.
> 
>
