### ISSUE TITLE
Signing up to a workspace briefly shows incorrect workspace front page

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#3232]
When signing up to a workspace, its front page first loads like the student would not yet be a workspace student (lacks tools like diary, discussions, etc.) Visiting materials or simply refreshing the page then renders it correctly.

**Comment by anttiviljakainen** [comment]
Seems to be related to the delay with the event message from pyramus being handled in muikku. If the event is not handled before the page is loaded, it probably ends with this result.
