### ISSUE TITLE
Sender of timed notifications seems to be their recipient

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#3235]
All timed notification messages appear to be sent by the person receiving them. Would probably be better if they were sent by a system account or something.

#### Details

 - Add text "this is an automatically sent message, don't reply" to the notifications
 - <strike>Create a system user (no-reply) in Muikku and set is as the sender of the communicator message</strike>
 - <strike>The system user should be available in all installations</strike>
 - **Keep the sender as-is**

**Comment by anttiviljakainen** [comment]
Emails are sent by a system account but the communicator messages have the recipient as sender.

**Comment by anttiviljakainen** [comment]
Groom this, several options:
- Set the guider as sender (what happens when the guider doesn't exist?)
- Create a system-user account (acts as a normal user so someone should manage it)
- Create a special case system sender who cannot be replied to (most labor intensive to implement)
- Won't fix

**Comment by ilmoeuro** [comment]
The notifications should **say** that they're automatically sent.
