### ISSUE TITLE
Creation of temporary room by students

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#3243]
#### Details

 - <strike>Make sure that their history is preserved after they are destroyed (in case of bullying or other inappropriate situations)</strike>
 - The "options" view is preserved, except
   - Persistent rooms are not allowed (teachers can make them)
   - No password-protected rooms
   - No "members only" rooms
   - No "admins" or "owners" lists
   - No setting for logging conversations - they're always logged
 - Room is created by joining a room that doesn't exist yet

**Comment by RazgrizX** [comment]
New parameter added to converse, limit_room_controls (false by default).
Prevents certain fields to render in converse chat room config by checking var parameter of field of IQ stanza.
The list of fields to filter is a constant array in converse-muc.js
