### ISSUE TITLE
Issues for implementation of the new UI design

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#3248]
It would be a great idea to atomize rest of the new UI design for smaller issues and place them to milestones. Lankinen is about to leave for his vacation, so this should be done next week.

**Comment by onzag** [comment]
Wasn't this done already? Or we need to do it for the overall rest of the design?

**Comment by ninakurki** [comment]
Yes, I meant that you should do it for the rest of the design before Lankinen leaves for his vacation. It would be easier for me to plan future milestones if there is ready made issues.

**Comment by onzag** [comment]
@ninakurki @ilmoeuro https://docs.google.com/a/otavanopisto.fi/document/d/1xVhJcveKMe0dTeCcjg4VquMxRW-RUg5ofAbYJl1fBoE/edit?usp=sharing
