### ISSUE TITLE
Check if profile picture exists before trying to load it

### ISSUE THREAD

**Issue by anttiviljakainen** [otavanopisto/muikku#3314]
Before trying to load a user profile picture check its existence via a variable. Currently the code tries to load every profile picture even if they don't exist which only returns 404 from server.

Main components:
* REST endpoints returning users should return proper value for hasImage or hasPicture attribute for users and this value should be used at least for discussion and communicator
* Logged in user profile picture should be checked from session

**Comment by anttiviljakainen** [comment]
#3845

**Comment by jjlankinen** [comment]
This should be fixed in the #3845 issue
