### ISSUE TITLE
Startup High School: Fix for profile picture layout

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#3320]
Profiilikuvapallerosta puuttuu pari laitaa (ks. kuva).
![profiilikuvake](https://user-images.githubusercontent.com/26649131/27429288-55daf772-574d-11e7-8ca4-77d455d5cf9a.png)

**Comment by avukkonen** [comment]
Näyttäisi olevan kunnossa mergen jälkeen.

**Comment by avukkonen** [comment]
Ei ollutkaan. Vika oli kurssilla. Korjattu.
