### ISSUE TITLE
Startup High School: Continue Studies -button has no text on it

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#3322]
Opiskelijoiden etusivulla olevassa Tervetuloa takaisin -laatikossa olevan painikkeen teksti ei näy. Siinä kaiketi pitäisi lukea Jatka opintoja.

**Comment by avukkonen** [comment]
En pysty toistamaan ongelmaa.

<img width="763" alt="screen shot 2017-07-03 at 14 38 30" src="https://user-images.githubusercontent.com/3994573/27791369-598a40c2-5ffd-11e7-9235-bf35430fab11.png">
