### ISSUE TITLE
Startup High School: New message -button has no text on it

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#3325]
Keskustelualueella Uusi viesti -painikkeen teksti katoilee näkyvistä. Sivun latautuessa ekan kerran se näkyy ja sitten katoaa. Kun sivun päivittää, teksti tulee näkyviin. Eli tällainen on ja off -näkyvyystilanne on siellä.

**Comment by avukkonen** [comment]
Ei pysty toistamaan.
