### ISSUE TITLE
Some of the courses are placed at the wrong place

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#3334]
VOPS:ssa on tarkoitus on näkyä vain ne kurssit, joille on oikeus ilmoittautua. Joissakin tapauksissa tarjottavia kursseja puuttuu välistä, jolloin niiden kohtien pitäisi olla tyhjiä kurssimatriisissa. Tällainen on esim. ÄI, jossa ei ole tarjolla kursseja ÄI7 tai ÄI10. Nyt matriisissa ÄI8-kurssi on kohdassa ÄI ja 7, loppurivi menee siis pieleen. Tällaisia tilanteita on myös muissa aineissa.

**Comment by ilmoeuro** [comment]
Duplicate of #3258
