### ISSUE TITLE
Workspace - archived students are not showing as archived.

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#3348]
>Minulla oli yksi opiskelija, joka korotti numeroaan. Minä siis olin arkistoinut opiskelijan kurssilta ja olisin sitä kautta mennyt hänen tietoihinsa ja antanut uuden arvioinnin kurssista,mutta eipä löytynyt opiskelijaa arkistoiduista. 

>Annukka sai lisättyä opiskelijan kurssille ja vasta sitten pääsin käsiksi. Huvikseni tein muutaman pistokokeen ja katsoin löytyykö arkistoituja opiskelijoita kursseilta ja kaikkia ei löydy. Onko tämä joku tekninen vika?

>Kyse oli nyt GE1 Sininen planeetta kurssista.
Eilen en löytänyt sieltä Heidi Kuupakkoa (aineopiskelija) ja nyt kun katsoin joitain, niin esim Ida Tuominen on suorittanut kurssin ja olen arvioinut sen 21.4., mutta ei löydy arkistoiduista, samoin Anniina Reijonen, arvioitu ja arkistoitu 20.4. Nämä vain muutama, jotka listalta katsoin. Toki paljon löytyy arkistoituneitakin

This should be studied. I asked Annukka what she did to correct the situation and she told she added the people to the workspaces in pyramus.

It could be that there has been a misunderstanding here and there are two separate workspaces involved - which would explain why the archived students did not show. 

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1839

**Comment by pkukkon** [comment]
Cleanup service now running, should now properly sync status between Muikku and Pyramus.
