### ISSUE TITLE
Workspace materials - Quote styles

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#3361]
Saila Karjalainen:

>Korostettu sitaatti -tyyliä on käytetty tähän mennessä materiaaleissa tuskin lainkaan tai ihan yksittäisiä kertoja. Sitaateissa käytetään joko Sitaatti-tyyliä tai Pitkä sitaatti -tyyliä. Kässäreissä tulee välillä tarvetta/pyyntöjä "nostoille", jolle meillä ei ole omaa tyyliä tai muuta vakiintunutta tapaa. Voisiko Korostettu sitaatti -tyyliä muokata niin, että sen nimi olisi Nosto/Nostotyyli. Tyylin voisi muuten jättää lähes ennalleen, mutta lainausmerkit voisi poistaa. Myös pystyviivan väriä voisi miettiä uudelleen, nyt siinä on tummanpunainen, joka on vähän poikkeava Muikun muusta värityksestä.

>Tällä ei kiire, mutta käytin jo tätä tyyliä sellaisessa paikassa, joka ei ollut sitaatti, vaan nimenomaan nosto.

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1860

**Comment by jjlankinen** [comment]
We need to replace the old style to keep markup as semantic as possible. Now there's material-citation-highlight and we can't keep that class name as the new style is only highlighted text. This change also requires manually fixing the workspace materials where old style was used.
