### ISSUE TITLE
Frontpage "New messages" widget too long

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#338]
Looks stupid. See att file. 
![nayttokuva 2015-08-07 kello 8 57 59](https://cloud.githubusercontent.com/assets/7565830/9129587/7898055c-3ce2-11e5-889b-f19eefa74b46.png)

**Comment by anttiviljakainen** [comment]
Server side needs paging support for this

**Comment by anttiviljakainen** [comment]
Fixed in https://github.com/otavanopisto/muikku/tree/BUG-338-communicator-pagination

Merged to devel
