### ISSUE TITLE
Workspace materials - new box style for diary entry

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#3422]
Saila Karjalainen:

>Voisi miettiä, onko tarvetta tehdä oma tyylilaatikko sellaisia kohtia varten, jossa opiskelijaa pyydetään kirjoittamaan oppimispäiväkirjaan. Yleensä sellaiset sisällöt sopivat Pohdintalaatikkoon, mutta eivät aina. Lisäksi pohdintalaatikolle on muutakin käyttöä (mielessä pohtiminen tai jopa tehtävään vastaaminen)

**Comment by avukkonen** [comment]
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1903#note

**Comment by jjlankinen** [comment]
This is done.
