### ISSUE TITLE
VOPS: Tarjolla olevat kurssit

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#3436]
Tarjolla olevissa kursseissa on vähän säädettävää ja tätä olisi hyvä groomata ennen kuin ryhdytään korjaamaan. Selvitettäviä kysymyksiä:
- Millä perusteilla tarjolla olevat kurssit näkyvät VOPS:ssa?
- Näkyvätkö siis molempien opsien mukaiset kurssit?
- Toimiiko HOPS-lomakkeen kielivalinnat? Vaikuttaa, että ei.

Ohjaajilta tuli näkyviin kursseihin lisäksi seuraavanlaisia kommentteja:

- Mediasta toinen kurssi pois, vain yksi kurssi on tarjolla. ME1 ok
- MAB2 on pakollinen kurssi (nyt sen kohdalla on neliö)
- Muuallakin on joidenkin kurssien kohdalla neliö. Esim. MU1-2, KU1-2
- Miksi näkyy ME10 ja AT9 -kurssit, niitä ei ole meidän opetussuunnitelmassa olemassa?
- Huom! Valokuvailmaisu on ainetta MUU. 
- 1.8. alkaen alle 18-vuotiaalta poistuivat pakolliset kurssit: LI1, TE1, kaksi kurssia taideaineita-> TE1, LI1, KU1-KU2 ja MU1-MU2 valtakunnallisiksi syventäviksi. (tällä hetkellä MU ja KU eivät kuulu mihinkään kategoriaan) >> Tällä hetkellä kuuluvat sekä pakollisiin että valtakunnallisiin syventäviin, koska näin oli vanhassa opsissa. Tätä ei voi muuttaa Pyramuksessa ennen kuin ollaan varmoja, että tilanne on tämä opiskelipa kumpaa opsia tahansa.
- Aineita vielä hieman väärässä järjestyksessä. Esim. MUU kuuluisi loppuun ja MAY mieluummin matikan (MAA tai MAB) yhteyteen. 
- TO1 puuttuu kokonaan.

**Comment by ilmoeuro** [comment]
All development for this is done, rest is settings.
