### ISSUE TITLE
Make sure language selections are not swapped

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#3447]

**Comment by ninakurki** [comment]
Tuleeko VOPSiin näkyviin nuo valitut kielet, vaikka meillä ei ole uuden opsin mukaisia kursseja näistä tarjolla? Jos tulevat näkyviin siihen ainelistaan, tämä ei toimi, koska nyt VOPSiin ei tule näkyviin mitään kieliä. @ilmoeuro
