### ISSUE TITLE
Mid-term (interim) course evaluations

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#3462]
As a teacher I want to be able to assess a student's progress even before they complete the course.

#### Source

Nyt väliarviointi toimii hyvin vanhassa arviointinäkymässä, mutta kirjoitan tämän tiedoksi, jos vanhasta arviointinäkymästä halutaan joskus luopua.

Uudesta arviointityökalusta puuttuu kurssin arvioiminen keskeneräiseksi. Jos opiskelija haluaa kurssista väliarvioinnin, niin täydennettäväksikin arvioitu kurssi on mielestäni selvästi väärin. En myöskään haluaisi antaa arvosanaa tehtäväkohtaisesta arvioinnista. (Siinäkin on nyt pakko antaa arvosana 4-10 tai arvioida tehtävä täydennettäväksi.)

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1929

**Comment by jjlankinen** [comment]
Closing this as duplicate, we have couple of other issues regarding the same feature with better and updated information.
