### ISSUE TITLE
After deleting message thread browser tries to reload the deleted thread

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#350]
Should send back to the discussion area under the the topic the deleted thread was. 

![nayttokuva 2015-08-18 kello 12 06 35](https://cloud.githubusercontent.com/assets/7565830/9326392/10f683ec-45a2-11e5-8ee3-7e6835246111.png)

**Comment by issakainen** [comment]
Nope.

![nayttokuva 2015-08-19 kello 14 53 29](https://cloud.githubusercontent.com/assets/7565830/9355453/136ad250-4682-11e5-9ab1-ae76e5bbb8a3.png)

**Comment by avukkonen** [comment]
Works!
