### ISSUE TITLE
Frontpage - the "continue studies" navigation is sometimes off.

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#3501]
Student says 

Etusivulla keskellä on kohta "kävit viimeksi työtilassa (esim. ue 1), 
jatka siitä mihin jäit". Se ei toimi. Minulla on ollut siinä sama kohta 
näkyvillä ainakin noin viimeiset 4 vkoa, vaikka olen tehnyt eri kursseja 
lukuisine eri tehtävineen tänä aikana.

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1966

**Comment by avukkonen** [comment]
The issue is real, it could be seen when signed as the student. The student had been studying in other courses, but the "continue studies"- link had failed to update. 

As soon as I went on to student's courses, it updated.

**Comment by avukkonen** [comment]
There is another issue of this:

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1968

**Comment by onzag** [comment]
This sounds like it is backend related, since the data comes from a  rest endpoint, any info on this, I am somewhat lost on backend related issues.

**Comment by onzag** [comment]
This was fixed right?
