### ISSUE TITLE
New message -discussion area dialog missing "Title" helptext

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#351]
Should guide the user on what goes on and where. See att pic.
![nayttokuva 2015-08-18 kello 12 36 04](https://cloud.githubusercontent.com/assets/7565830/9326899/e7d821e2-45a5-11e5-90de-407bec2c25c1.png)

**Comment by jjlankinen** [comment]
Fixed by adding title similar to communicator's new message view.
