### ISSUE TITLE
Changing username

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#359]
User can't change his / hers username without also changing the password - or typing in the old password in all three fields. It should allow changing the username just by typing the new one in and then confirming it by asking the current password. 
![nayttokuva 2015-08-19 kello 22 00 22](https://cloud.githubusercontent.com/assets/7565830/9366096/ee11781a-46bd-11e5-94cf-fd970f8c6d44.png)

**Comment by jjlankinen** [comment]
Fixed by checking if user hasn't entered a new password(s), then we update only username and require old password.
