### ISSUE TITLE
"New student has signed-up to your class" -message

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#360]
See att pic and change the layout as it is shown. 
![nayttokuva 2015-08-20 kello 12 55 26](https://cloud.githubusercontent.com/assets/7565830/9380742/d7cabbb6-473a-11e5-8295-791d76ecd62b.png)

**Comment by avukkonen** [comment]
Where does the student name link to?

**Comment by ilmoeuro** [comment]
Student link points to student's guider profile.
