### ISSUE TITLE
Preserve chat messages for more than 2 days

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#3607]
#### Details

 - Increase to 5 days, that way (a) staff can respond to questions on Monday that are asked Friday and (b) students have time to find pairs etc
 - Also check if messages can be preserved across restarts

**Comment by RazgrizX** [comment]
This can be achieved with installing "Monitoring Service" plugin in Openfire plugins.
Configuration is available in "Server -> Archiving" tab.
Message archiving need to be enabled (3 options, select all).
Max age and Retrievable messages options are self explanatory and can be set to needed value.
Statistics are provided once message archiving is enabled.
Messages are stored in database used by Openfire.
Messages are available after server restart.
Also messages can be viewed in "Search Archive" tab.

**Comment by RazgrizX** [comment]
[properties.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a12ab4a822d2b0013e7cf28/125516c66e82c728ace21e0d46f88695338791bd86ecac01e81fe086264c22703d46f96925d6bb7bee1a28040a0d1bfa485f0d45aaf08c22f0b33b26984019af80330b2b9b645bf9fa9015ad00bc2a8a4a84b5be894bc8ea392de08d9d02.txt)

**Comment by petja-laitila** [comment]
These lines for the plugin in question
conversation.idleTime;360
conversation.maxAge;5
conversation.maxRetrievable;5
conversation.maxTime;3600
conversation.messageArchiving;true
conversation.metadataArchiving;true
