### ISSUE TITLE
Renew evaluation date when re-evaluating incomplete evaluation

### ISSUE THREAD

**Issue by anttiviljakainen** [otavanopisto/muikku#3658]
If evaluation is saved as incomplete, the date of the following re-evaluation is often mistakenly saved as the old incomplete evaluation date.

Make it either easier to notice the date is old or automatically fill in the new evaluation date when saving the new evaluation.
* If the date is always updated automatically, is there a situation (like fixing a typo etc edit) when it shoudn't update?
* If the date is not updated automatically, what kind of indication would be sufficient?

SH: Elise, Riitta, Annukka(?)

**Comment by pkukkon** [comment]
Groomed in the daily of 29th January. It was agreed that it is sufficient to change the workspace (and individual assignment) editors so that the evaluation date is always set as current date, even when editing existing evaluations.
