### ISSUE TITLE
Workspace materials - counter for memofield

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#3757]
Teacher: 

>Keväästä 2018 lähtien kielten yo-kokeissa kirjoitelmien ohjepituudet ilmoitetaan sanojen sijaan merkkeinä (ilman välilyöntejä ja rivinvaihtoja). Muikun tehtävänannotkin luultavasti vähitellen päivittyvät merkkimääräisiksi kielten kursseilla. Olisiko mahdollista lisätä Muikkuun tällainen laskuri muistiokenttään?'

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=2140

**Comment by jjlankinen** [comment]
We can add letter count to memo and CKEditor fields with word count information.
