### ISSUE TITLE
Communicator sends messages to former students

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#3758]
If a student who has ended their studies belongs to a user group, and a communicator message is sent to that user group, the former student also gets this message (and a subsequent email notification about a new message in Muikku).

Due to some people not preferring to receive any mails after they have ended their studies, this functionality needs to be re-evaluated. Some possible fixes:

- don't send communicator messages to inactive students
- don't send communicator message email notifications to inactive students
- add an option to send group messages to everyone or just active members of the group
- something else entirely?

Note that we also have a group for ex-students (ex-nettilukiolaiset) so if that is used for communicating, the fix has to be such that it won't break this functionality. Then again, it should also be checked whether former students even have access to communicator anymore (they can most likely sign in but I recall they only have access to guider in order to view their study history).

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=2161

**Comment by jjlankinen** [comment]
We should not send any communicator messages to inactive student and therefore we prevent any email notifications.
