### ISSUE TITLE
Changing username fails if new username is already in use

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#3798]
Changing credentials has no logic whatsoever to deal with usernames that are already in use (apart that the change itself fails due to a duplicate).

**Comment by jjlankinen** [comment]
Error message should read: Käyttäjätunnus on jo käytössä. / Username is already in use.

**Comment by saaralepisto** [comment]
#710

**Comment by saaralepisto** [comment]
https://github.com/otavanopisto/pyramus/issues/710
