### ISSUE TITLE
Better error pages

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#3801]
Muikku has some views for common error situations...
- /error/not-found.jsf
- /error/access-denied.jsf
- /error/internal-error.jsf
...and one uncommon, that could probably be handled as a notification queue message...
- /error/auth-no-email.jsf
...but all of them are rather fugly and need a proper design/layout if we are going to utilize them better in the future.

**Comment by jjlankinen** [comment]
This should be done already.
