### ISSUE TITLE
Guider dialog - problem with the autocomplete

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#3810]
Autocomplete flows inside the dialog box and if the box is very small, it looks stupid.

Fixed by putting a min-height to the content -
 looks stupid, but not that stupid.

Can be seen in the "share flags"-dialog.

**Comment by jjlankinen** [comment]
This has to be redesigned properly as of now it really looks bad and is almost unusable.

**Comment by onzag** [comment]
Why is the design broken?... I mean it was functional before (and it was actually quite hard to setup) and it seems to be just a css issue, I will try to check it out to see what I can do.
