### ISSUE TITLE
Guider - add files to student

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#3812]
There is a add file dialog, but when the file is chosen, nothing happens. 

Tested in firefox.

**Comment by onzag** [comment]
`insert into PluginSettingKey (name, plugin) select 'fileUploadBasePath', 'transcriptofrecords' from PluginSettingKey where plugin = 'transcriptofrecords' and name = 'fileUploadBasePath' having count(*) = 0;`

**Comment by onzag** [comment]
`insert into PluginSetting (value, key_id) select '/home/yourhome/somefolderyoucanuse/', id from PluginSettingKey where plugin = 'transcriptofrecords' and name = 'fileUploadBasePath';`

**Comment by onzag** [comment]
You need to run those in muikku database and replace `/home/yourhome/somefolderyoucanuse/` to some folder the app can use

The design is pretty crappy at this point I suppose none managed to style it because of this, this is not an issue, it is lack of configuration.

**Comment by onzag** [comment]
Reassigned so that someone can style it to call it a day.

**Comment by jjlankinen** [comment]
Need to fix my db so I can verify this and make it look good.
