### ISSUE TITLE
Cleanup and Debug

### ISSUE THREAD

**Issue by onzag** [otavanopisto/muikku#3859]
cleanup and debug,
this is not a task per say but it compiles all the cleanup and debugs tasks together in order to have a single branch for them.

**Comment by onzag** [comment]
Fixes #3858

**Comment by jjlankinen** [comment]
Fixes #3868 Index page has been cleaned for now.

**Comment by jjlankinen** [comment]
Front page, Index, coursepicker, announcer, discussions, communicator done.
