### ISSUE TITLE
Thread reply cannot be deleted

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#3890]
In thread view messages that are replies cannot be deleted. After clicking delete button in dialog thread just reloads.

**Comment by onzag** [comment]
@jjlankinen as I see messages are not meant to be deleted but their content is... a deleted flag appears in the message, what I did to fix this bug was to show a [deleted] message just like in reddit, but needs translation.

**Comment by jjlankinen** [comment]
I added the "missing" locale string that existed already.
