### ISSUE TITLE
Sticky message should shorten message content

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#3897]
When message is set to sticky in discussion,  message listing view loads sticky message with it's content but it should be shortened to lets say 255 characters instead of showing full message content. 

Message content is only visible in said view with sticky messages.

**Comment by onzag** [comment]
@jjlankinen does this happen only with sticky?...

**Comment by onzag** [comment]
I don't understand :(

**Comment by onzag** [comment]
Ok this is solved with a mechanism of a overflow detector with a gradient, it wasn't easy, but it's done :)
