### ISSUE TITLE
Message search

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#3901]
Search feature is needed in communicator. 

Search should be text search and it needs to search from labels, recipients, senders and dates.

Search needs to search form every folder's messages.

**Comment by onzag** [comment]
@saaralepisto you might be able to start on this issue, it needs some server side changes to expand how you retrieve items from each location, these are inbox, unread, sentitems, items and trash; currently it takes firstResults, maxResults, onlyUnread; we need to have the query option.
