### ISSUE TITLE
Records - Student who has finished studies should see finishing date

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#3940]
Student send this picture:

![kuva](https://user-images.githubusercontent.com/3994573/37888981-ea248a7e-30d2-11e8-9964-5810fe3ba468.png)

Student's study time is still running, even though he/she has finished studies.

# Helpddesk issue:
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=2277

#### Details
We should hihde study time if student has finished hes/hers studies.

**Comment by onzag** [comment]
@avukkonen this is almost done, just need to add the correct translation for "plugin.records.studyEndDateLabel" do a pull and restart the server this needed some server side fiddling.
