### ISSUE TITLE
Guider won't work when student has not filled HOPS form

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#3944]
Guider reports error "e.hops is undefined" is student has not filled HOPS form.

This has to be checked if student has VOPS activated in the first place and then it has to be checked is HOPS form is filled out.

**Comment by onzag** [comment]
This should be fixed, it currently works in my branch, note that I have deactivated the mocking of the hops and vops.

Also the design goes out of whack when vops and hops are not available (student not opted in in those); please fix to get this issue closed :)
