### ISSUE TITLE
Mobile device can't scroll view properly

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#3976]
In evaluation when assignment has big image or video as a first paragraph teacher can't scroll the view when using mobile devices as both image and video has some sort of event binded to them.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=2302

#### SH
Päivi putkonen

**Comment by jjlankinen** [comment]
Images should not have click event so they behave as normal images. Videos should not have click event. We could add link to said video.

**Comment by TeroOtavia** [comment]
Seems that after evaluation rework, this issue doesn't exist anymore. Tested in development enviroment and production.
