### ISSUE TITLE
Better error message if discussion has no areas

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#3977]
If discussion has no areas created and user tries to create new message he/she gets "Not found" error message which does not hint what is wrong.

This happens mostly in workspsace discussions as teachers might not remember to create discussion areas.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=2306

#### 
Lasse Hoffmann

**Comment by onzag** [comment]
There are actually many problems with the error messages, in some parts say while creating new messages, the error just displays HTML, currently ; we need to take care of these errors and create translation strings for them

**Comment by onzag** [comment]
???????? the issue suddenly closed....

**Comment by onzag** [comment]
The issue suddenly closed?????
