### ISSUE TITLE
Load labels containers only if item has labels/flags

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#3978]
It needs to be checked if optional content is loaded or not so we don't put unnecessary elements in the markup as those elements might have padding or margin value set and they take up space even when empty.

This mostly concerns labels and flags containers as they are put in markup even if messages/students don't have any labels/flags.

**Comment by onzag** [comment]
What is that container? There are many containers that contain labels.

**Comment by jjlankinen** [comment]
We have labels in communicator and guider (flags) and they are loaded inside application-list__item-footer element. This element should not be rendered if student or message has no labels/flags.
