### ISSUE TITLE
Uploaded files won't show on low resolution displays while in evalution

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#399]
See att pic. The link to the file is barely visible. 
![nayttokuva 2015-09-18 kello 8 52 17](https://cloud.githubusercontent.com/assets/7565830/9952813/c9871c20-5de2-11e5-852b-b00e81c5d67f.png)

**Comment by jjlankinen** [comment]
Fixed by forcing margin value with !important property, not elegant but works.
