### ISSUE TITLE
Incomplete status missing in studies

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#3990]
Workspace specific incomplete status is missing, only passed and failed can be shown in studies view per workspaces.

**Comment by onzag** [comment]
How do you want this to be visualized? I was unable to see a different state during my checking with the pre-redesign version; only passed and failed seem to have a state; can you give me some examples of what is expected in each workspace; right now:

1. If there is no assessment it will show the activity.
2. If there is an assessment it will display the resulting evaluation, and add a class on wheter passed or failed.

Right now for the assessment there is an unused variable `workspace.studentAssessments.assessmentState` this can take the values "unassessed" | "pending" | "pending_pass" | "pending_fail" | "pass" | "fail", it is also accessible from within the student acitivity, if it found no assessment; as in workspase.studentActivity.assessmentState.state

**Comment by pkukkon** [comment]
Adding "incomplete" to assessmentState in #4008.
