### ISSUE TITLE
Evaluation request missing in studies

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#3991]
Workspace specific evaluation request information is missing in studies view. When student creates eval. request it should be displayed in studies view with the workspace information.

**Comment by onzag** [comment]
This is fixed now, a couple of new classes have been added to the workspace.tsx class file in guider; oh wait, STUDIES, well I fixed another bug then, check it out anyway; now you have course--pending-assessment and so on that needs styling.
