### ISSUE TITLE
Study end time missing

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#3999]
Studies view is missing students study end time. 

Date and time in study start time is also in wrong format as it produces invalid date.

Guider and studies view seems to handle start and end times and dates in different time format based on console output.

**Comment by petja-laitila** [comment]
Seems to be fixed in FTR-3882-studies-styling-fixes

**Comment by jjlankinen** [comment]
Same issue as #3940

If student has ended hes/her studies "right to study end time" should be displayed as studies ended time.

**Comment by onzag** [comment]
Oh, this is about text; ok I will do it.

**Comment by onzag** [comment]
Removed bug and added enchacement since such property is not available in transcript of records, there's no date on when the studies ended it needs to be added server side.

**Comment by pkukkon** [comment]
Added studyEndDate to ToR backing bean
