### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by onzag** [otavanopisto/muikku#4061]
Missing translations in `/actions/messages/index.ts` search for `Invalid navigation location` which is hardcoded.

**Comment by onzag** [comment]
Also in english
![Selection_089.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d8a72c0292df00200e714a/125516c66e82c728ace21e0d46db9196268197a080e78013fc04b2d86b56357c2301a03f32dfa17dec1a2850575c1bf9130d094dfbab887dafb335268f5b5dffcd7f1d2598694ef1e1c84afd13b0328a488fb7b9884bc5e13e22e48e87483c0c48.png)

And this one is misleading
![Selection_090.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d8a72c0292df00200e714a/125516c66e82c728ace21e0d46db9196268197a080e78013fd0db2d86b56357c2301a03f32dfa17dec1a2850575c1bf9130d094dfbab887dafb335268f5b5dffcd7f1d2598694ef1e1c84afd13b0328a468fb7b9884bc5e13e2de589874a370c48.png)

There are a couple of problems with that one give that first, answer message is cropped, and second is that we are in edit mode, so the text in the messages is wrong.

**Comment by avukkonen** [comment]
I think I did this with in the #4011
