### ISSUE TITLE
Communicator: confusing workspace recipient

### ISSUE THREAD

**Issue by anttiviljakainen** [otavanopisto/muikku#4134]
Communicator allows selecting workspace as a recipient, but in no way indicates that the message is received by both students and teachers. This causes confusion in some students who think it's only for reaching teachers.

Couple of possible fixes:
1. Indicate clearly that the workspace as recipient is both teachers and students
2. Pop up a warning message about who the message is being sent to
3. Differentiate the recipient groups to two different groups (as it was originally) with "<coursename> teachers" and "<coursename> students"

**Comment by jjlankinen** [comment]
We can remove students privileges to send messages to workspaces.

**Comment by onzag** [comment]
Followup server side issues #4143 #4144
