### ISSUE TITLE
Charts to display student's overall activity

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4135]
Create chart specific to show student activity that is accessible for teachers. Chart design and placement is questionable and needs grooming. A dropdown with more data could be displayed on click on the chart or clickable icon, placed next to logged in data visible in guider.

**Comment by RazgrizX** [comment]
The branch is ready, it is only a prototype.
The ad of the amChart is hiddent using line-height, which may violate the terms of use.
DO NOT MERGE before the legal status is determined, or the licence is bought.

Might have problems in the mobile view, since the second part of e-mail is not limited.

**Comment by jjlankinen** [comment]
Mostly done.
