### ISSUE TITLE
Communicator next/previous message buttons "reversed"

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#4142]
When opening a message in communicator, moving to the next (older) message is currently tied to the left (<) navigation button whereas, for example, Google Mail does this the other way around.

Would feel more logical that right (>) moves to the next (older) message and left (<) back towards the more recent message.

**Comment by jjlankinen** [comment]
This swap between prev and net navigation buttons within communicator messages is done in demo-issues-vol3 branch.
