### ISSUE TITLE
Filter Workspaces in the server side for communicator messages

### ISSUE THREAD

**Issue by onzag** [otavanopisto/muikku#4143]
As of currently all workspaces are sent to the communicator messages as recepients even if they are not mean to have access to.

Basically putting the situation where a teacher is sick and decides to send a message to all his workspaces, the students of each workspace receive the message including all those other workspaces as recepients, you can attempt to replicate and you will see the student sees the other workspaces.

A client side filter doesn't suffice since I don't know which workspaces the student has access to.

This affects both the list all messages and display one single thread.

The fix has to be careful, and it has to consider what would happen once the student loses access to that workspace in question, then the recepients will be blank in old messages?

The student should be able to see the workspace that made him receive the message in order to know the context.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=2455

**Comment by jjlankinen** [comment]
After thorough grooming we decided this as a non-issue. If in future another stake holder disagrees and requires changes we will groom this again.
