### ISSUE TITLE
Discuss and agree on event names 

### ISSUE THREAD

**Issue by RazgrizX** [otavanopisto/muikku#4182]
We can add new events easily, but it could be hard to change their names later. To avoid excess work we need to agree on the event naming.

Current names:
0   | EVALUATION_REQUESTED - evaluation request created
1   | EVALUATION_GOTINCOMPLETED - supplement request created
2   | EVALUATION_GOTFAILED - evaluation with non-passing grade created
3   | EVALUATION_GOTPASSED - evaluation with passing grade created
4   | SESSION_LOGEDIN - uses login event listener (same as mongo)
5   | WORKSPACE_VISIT - workspace visit controller
6   | MATERIAL_EXERCISEDONE - material reply created type EXERCISE
7   | MATERIAL_ASSIGNMENTDONE - material reply created type EVALUATED
8   | FORUM_NEWMESSAGE - thread reply created
9   | FORUM_NEWTHREAD - new thread created
10 | NOTIFICATION_ASSESMENTREQUEST
11 | NOTIFICATION_NOPASSEDCOURSES
12 | NOTIFICATION_REQUESTASSESMENTSUPPLEMENTATION  (isn't it too long?)
13 | NOTIFICATION_STUDYTIME (not representative? maybe STUDYTIME60DLEFT?)

**Comment by jjlankinen** [comment]
I don't see any problems with those strings. Using literal strings is actually easier to read and interpret.

**Comment by anttiviljakainen** [comment]
On a friday afternoon I can't come up with anything better.. All I would do at this point is fix couple of typos:
LOGED_IN -> LOGGED_IN
EXCERSISE_DONE -> EXERCISE_DONE

**Comment by RazgrizX** [comment]
Ok, fixed them in the code

**Comment by pkukkon** [comment]
NOTIFICATION_REQUESTASSESMENTSUPPLEMENTATION could be just NOTIFICATION_SUPPLEMENTATIONREQUEST, otherwise fine.
