### ISSUE TITLE
New private message: Title Field Background Color missing (active vs inactive)

### ISSUE THREAD

**Issue by jarkkoh** [otavanopisto/muikku#421]
![new_message](https://cloud.githubusercontent.com/assets/3033999/10067729/6dc7b54c-62a7-11e5-9e5e-ae57d194a04a.gif)

**Comment by jjlankinen** [comment]
Background should be visible when title field is activated. Does it not work like that?

**Comment by jarkkoh** [comment]
Sorry, new PRIVATE message/reply.

**Comment by jarkkoh** [comment]
Not fixed (staging)

**Comment by jarkkoh** [comment]
.mf-content .mf-fieldRow .mf-textfield input[type="text"].mf-textfield-subject:hover {
  background-color: #fff;
}

Should be:

.mf-content .mf-fieldRow .mf-textfield input[type="text"].mf-textfield-subject:hover {
  background-color: #eee;
}

**Comment by avukkonen** [comment]
And focus too. I checked both in the devel branch and they are like they should be.

**Comment by avukkonen** [comment]
I tested in staging, the problem exists. It's likely a build issue. In dev branch _mainfunctions.sccs has the correct color values.
