### ISSUE TITLE
Hakemusten poistaminen

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#4226]
Uuden hakemusjärjestelmän hakemusten poistaminen pitää ratkaista jollain tavalla. Poistamisen pitää tapahtua oikeasti, ei siis riitä, että hakemus jää taustalle killumaan.

Poiston toivotaan tapahtuvan seuraavilla tavoilla:

**Heti**
Aineopiskelu > lomakkeen hylkäys > poisto heti

**Vuosi jättöpäivästä**
Aineopiskelijoiden rekisteröitymislomake > vuoden jälkeen rekisteröitymisestä
MK-linjan ja aikuislukion hakemukset > vuosi
Nettilukio / nettiperuskoulu, **mikäli ei siirretty opiskelijaksi** > vuosi

**Opiskelun päättymispäivä**
Nettilukio / nettiperuskoulu > hakemus poistetaan, kun opiskelijalle kirjataan opiskelun päättymispäivä

**Comment by pkukkon** [comment]
Pyramus PR https://github.com/otavanopisto/pyramus/pull/900
