### ISSUE TITLE
Scores for student's overall activity chart actions and colors

### ISSUE THREAD

**Issue by RazgrizX** [otavanopisto/muikku#4244]
The scores for the chart need to be developed.
All the actions / events may have a number of points given for each one of them performed.
This way all the activity converted into single line.
 
1.  EVALUATION_REQUESTED,
2.   EVALUATION_GOTINCOMPLETED,
3.   EVALUATION_GOTFAILED,
4.   EVALUATION_GOTPASSED,
5.   SESSION_LOGGEDIN,
6.   WORKSPACE_VISIT,
7.   MATERIAL_EXERCISEDONE,
8.   MATERIAL_ASSIGNMENTDONE,
9.   FORUM_NEWMESSAGE,
10.   FORUM_NEWTHREAD,
11.   NOTIFICATION_ASSESMENTREQUEST,
12.   NOTIFICATION_NOPASSEDCOURSES,
13.   NOTIFICATION_SUPPLEMENTATIONREQUEST,
14.   NOTIFICATION_STUDYTIME

Also, the colors the chart uses should be agreed on, as well as the monthly score thresholds score needed to achieve to make a chart of the specific color.
at the moment
0  #FF0000 DEAD
1 -100 #FF8000
100 - 150 #FFFF00
159 - 200 #80FF00
200 - 250 #00FF00

**Comment by jjlankinen** [comment]
Very unlikely that we will work on this i the future. Re-open if necessary.
