### ISSUE TITLE
Study guider/teacher can't see students courses

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4309]
Study guider can't see students courses nor assignments who are part of his usergroup when viewing said students in guider.

Study guider should have access to students courses even if they are incomplete and not yet evaluated.

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=2449

**Comment by jjlankinen** [comment]
Actually nobody can see those things in guider as it lacks that feature.

**Comment by avukkonen** [comment]
Fast way to provide a fix fo this in #4714

**Comment by saaralepisto** [comment]
Already done
