### ISSUE TITLE
Workspace redesign.  All announcements showing for admins

### ISSUE THREAD

**Issue by petja-laitila** [otavanopisto/muikku#4318]
Workspace frontpage shows all announcements without making distinction between general and workspace announcements. Used to show only announcements of that specific workspace.

**Comment by petja-laitila** [comment]
Seems to be working in FTR-4087_materials-redesign

**Comment by petja-laitila** [comment]
Working as should for students. Administrators see all announcements.

**Comment by onzag** [comment]
Students also see all the announcements, hideEvironmentAnnouncements has been now set to true for everyone.
