### ISSUE TITLE
Discussion category does not load properly

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4398]
In production only 1 discussion area shows category correctly, other 2 fails to load the category color.

**Comment by onzag** [comment]
Discussion category uses the forumAreaId as the category number, I don't know how this was designed to be or why that is the case; what is supposed to be the logic behind categories?...

**Comment by onzag** [comment]
@jjlankinen

**Comment by jjlankinen** [comment]
Every category has different color assigned to it ad that color should be displayed with the message.

**Comment by onzag** [comment]
there's no color assigned to any category, they are just literally set in the scss based on their ID
