### ISSUE TITLE
Improved grades support with versioning

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4400]
Evaluation needs support for improved grades assessments.

When student's course has been evaluated as passed there is 2 week window for student to request additional assignments to improve hes/her grade. 

Evaluation view's course assessment form needs new radio button called "Improve" (or something similar) to indicate new version of grades improving assessment will be created. This will create new version that will be visible in Pyramus as well. New grade improving assessment will be current assessment i n Pyramus and previous assessment will not be editable anymore.

In Pyramus students course grades tab should show only improved grade assessment and grade info should be marked with asterisk to indicate improved grade. Complete version history should be visible in course assessment view and only the latest assessment should be in editable form.

Multiple changes for course assessment are required:

* Editing previously made course assessment should be possible until improved grade has been set. After that assessor can only edit the assessment for improved grade.

* Assessment date should not update automatically to the present day when editing course assessment. It might be even disabled to prevent accidental double assessment.

* Double assessment warning will be irrelevant and assessor should not be able to create double assessments as date field will be disabled.

* After assessment for improved grade has been made we need to display some kind of history above course assessment form. There could be "Assessment history" title containing previous assessment as well as incomplete assessment (if given) nested under said title.

* Assessment history should not be visible if assessor has not made improving assessment or there are no incomplete assessments. If incomplete assessment has been made then history will be shown.

**Comment by pkukkon** [comment]
Issues addressed in #4454
