### ISSUE TITLE
Supported browsers list in guides are invalid

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4415]
Guides of Muikku lists invalid list of supported browsers. It indicates that Safari version 9 should be supported when in fact 11.0.2 can be the oldest version as webRTC (audio recording) support was added to that version.

It's recommended to say that last 2 versions of Chrome, Firefox and Edge will be supported. Safari 11.0.2+ will be supported for the time being as Apple handheld products does not support updating only Safari.

**Comment by ninakurki** [comment]
Siellä lukee nyt näin:

Firefox (viimeisin versio)
Chrome (viimeisin versio)
Microsoft Edge (viimeisin versio)
Safari (versio 11.0.2 ja tätä uudemmat)
