### ISSUE TITLE
Painolliset kyrilliset kirjaimet

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#4446]
Painomerkilliset kyrilliset kirjaimet tulostuvat Muikussa lihavoituina, mikä korostaa painomerkkiä turhaan. Käytännössä joka sanassa on painomerkki eli yksi lihavoitu kirjain.

ks. esim. tällä kurssilla:
https://otavanopisto.muikkuverkko.fi/workspace/veb32-matkalla-maailmassa/materials

**Comment by jjlankinen** [comment]
Ongelma luultavasti on ainoastaan Chrome selaimella. Luultavasti syynä on se että Chrome lataa lokaali version fontista jossa ei ole kyrillistä subset:tiä mukana jolloin painotetut merkit puuttuvat ja ne korvataan sekondäärisellä fontilla meidän tapauksessa Arial:lla.

Firefox ja muut selaimet toimivat oikein testien perusteella. Google web fonts sivustollakin voi törmätä tähän ongelmaan kun testaa fonttia oikealla subset:llä eli lokaali versio fontista latautuu välillä.

**Comment by ninakurki** [comment]
Joo, nyt kun sanoit, kävin katsomassa Firefoxilla ja sillä nää tosiaan näkyvät eri tavalla. Voiko tuolle Chrome-asialle siis tehdä mitään? Se on kuitenkin suhteellisen käytetty selain.

**Comment by jjlankinen** [comment]
Ilmeisesti ei ole suoraan kyseessä fontin lokaali version latautuminen sillä minulla ei ol koko Open Sans fonttia asennettuna. Testasin satumanvaraisella fontilla joka näennäisesti silloin tällöin toimi fonts.google.com palvelussa painotettujen (diacritics) merkkien suhteen mutta mikäli fontin lisää webbi saitille niin nämä painotukset eivät Chromessa toimi. 

Luultavasti liittyy jotenkin selaimen unicode range:n toimivuuteen sekä fonttien subset:ien latautumiseen. Asiasta on tehty bugi ilmoitus ja kysymys googlelle ja ei muuta kuin odotellaan nyt.

**Comment by jjlankinen** [comment]
https://github.com/google/fonts/issues/1702#issuecomment-463949368

**Comment by ninakurki** [comment]
Oiskohan tää mahdollista korjata? Siis olisiko tullut korjaus Googlelta?

**Comment by jjlankinen** [comment]
Ei ainakaan näytä olevan korjattu vieläkään.

**Comment by ninakurki** [comment]
Tämä on korjaantunut.
