### ISSUE TITLE
Muikku trying to find a single student group causes continuous 403 from Pyramus

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#4461]
Muikku UserGroupRESTService.findById (/usergroup/groups/{ID}) is called very frequently and constantly bangs its head on 403 from Pyramus (/students/studentGroups/{ID}) due to insufficient rights.

Temporarily fixed by adjusting Pyramus permissions but needs a more permanent fix by pinpointing who, where, why, and how calls that endpoint.

Introduced after Feb 6th update. Muikku server logs between then and today might be of help.

**Comment by onzag** [comment]
usegroup might be called when loading the index file that was patched... I assume this is the case.
