### ISSUE TITLE
Invalid REST call parametes

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#4462]
Unable to extract parameter from http request: javax.ws.rs.QueryParam("userId") value is {1} for public javax.ws.rs.core.Response fi.otavanopisto.muikku.plugins.workspace.rest.WorkspaceRESTService.listWorkspaces
Caused by: java.lang.NumberFormatException: For input string: ""

Unable to extract parameter from http request: javax.ws.rs.PathParam("USERENTITYID") value is {1} for public javax.ws.rs.core.Response fi.otavanopisto.muikku.plugins.user.rest.UserEntityFileRESTService.getFileContent
Caused by: java.lang.NumberFormatException: For input string: "null"

**Comment by onzag** [comment]
Where does this happen?...
