### ISSUE TITLE
Invalid announcer REST call

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#4492]
Client side is making invalid calls to /rest/announcer/announcements/{ID} with announcement id "NaN". Exact location unknown, will update with steps to reproduce if found.

**Comment by onzag** [comment]
@pkukkon I made a fix to check for NaN values but this is a sign of a malformed url in the browser url bar, now malformed urls will be ignored and behave like if they weren't there.

What is generating the malformed url is the question.
