### ISSUE TITLE
Editor in materials does not have state readonly when assignment has been submitted

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4530]
When student submits assignment for evaluation every task field in that page should be set to read only state, this does not happen with ckeditor currently.

**Comment by onzag** [comment]
Found another bug, which has been fixed, either way, cannot replicate.

State becomes readonly only in the case of EVALUATED assignments.

On exercises it remains able to change which changes the state back, it worked the same way in production.

**Comment by jjlankinen** [comment]
Editor should behave like in production with submitted assignments. Currently in production when user submits assignment memo fields and editors have disabled state to prevent further editing. Now when user submits assignment editor remains in editing state and user can still access the editors content which is not optimal as it does not (should not) get saved when the assignment has been submitted for evaluation already.

Memo field does get disabled properly though.
