### ISSUE TITLE
Taskfield's correct answer counter does not work properly

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4551]
Correct answers counter seems to be reversed. If every answer is correct regardless how many taskfields are per page counter shows 0 / 4 (or what ever the max value is)

Taskfields that have this problem are following: Connect field, sorter field, organizer field, select field with checkbox.

Text field and select field with list, dropdown and radio button works as they should.

**Comment by onzag** [comment]
I believe this is fixed, even when I could only find this on one of the fields (multiselect field).

I believe the others were affected by the other bug where the counter was missing, whereas in multiselect the value was reversed because it missed a negative.
