### ISSUE TITLE
Editing materials in code view, doesn't save

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#461]
If you edit your materials in code view, the editor stops saving. Issue from Nina: 

"Jos materiaaliin tekee muutoksen koodi-tilassa, tallentaminen lakkaa toimimasta. Ainoastaan editorin avaaminen uudelleen tehoaa, mutta koodi-tilassa tehty muutos ei tallennu.

Tällainen tilanne tuli vastaan, kun taulukkoon oli ilmestynyt tyhjästä ylimääräinen rivinvaihto, jota ei saa pois kuin koodi-tilassa (siellä on ylimääräinen <p></p> -tagi)."

**Comment by anttileppa** [comment]
The code view should be not there in the first place, so the appropriate fix would be to remove the button from the toolbar

**Comment by pkukkon** [comment]
Quick fix would be to remove the button. Appropriate fix would be to treat a visit to the Code view as the entire document content having been modified (from CoOps' perspective, at least). There are many situations where editing document contents in Code view would be exceptionally useful.
