### ISSUE TITLE
Request evaluation after incomplete evaluation does not change the state correctly

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4644]
UPDATE_WORKSPACE_ASSESSMENT_STATE needs to change to pending when students requests evaluation after he/she has received incomplete course assessment. Currently state remain incomplete and therefore icon and necessary colors does not change accordingly.

**Comment by onzag** [comment]
I think this is fixed but where does the message go for the supplementation request?

**Comment by jjlankinen** [comment]
If you mean the message student receives then it goes to the students communicator. Supplementation message should also be visible with the material page where literal assessment, grade and assessor details are placed.
