### ISSUE TITLE
Automatic saving does not have any kind of indication

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4814]
We need to figure out how we are going to inform users that assignments, exercises and other user inputted data is saved automatically. 

We use to add specific label to indicate the fields data was saved but I think we need to come up better solution. 

The main concern for this is we had this functionality before in material's assignments and exercises and users might expect the same behavior.

Child of #4087

**Comment by onzag** [comment]
I have passed this issue to you Lankkinen, the indication was implemented but needs to be properly interfaced.
