### ISSUE TITLE
Publish button gets activated too early

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4827]
When entering material page editor the publish changes button gets activated immediately even when there are no changes made.

This can cause problems as users have access to source view inside of that editor and pasting content there will not normally activate publish button. Now that the button is activated immediately it gives an impression that source view has changes that can be published and pressing that button does actually nothing at all.

Within source view user cannot publish changes currently. We don't need to change that yet.

Child of #4087

**Comment by onzag** [comment]
I pressume this issue comes from adding an empty space or a hidden character that was drafted in the draft system.

The draft system which is incomplete doesn't show a message when it loaded from the draft, and even an empty space would make it show the publish button.
