### ISSUE TITLE
Word definition does not work in materials

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4828]
When adding word definition nothing happens. User can select text and access work definition dialog but after adding text and confirming it via ok button the word definition is not applied.

Word definition should be visible in the editor and in material page.

Child of #4087

**Comment by onzag** [comment]
Seems to work just fine, tested as a student, non logged in student, teacher, in edit mode and afer a modification; it works consistently. Please recheck.

**Comment by onzag** [comment]
Pasi fixed it

**Comment by jjlankinen** [comment]
Currently <mark> element is nested with div and that breaks page flow. If there has to be some sort of wrapper for <mark> element then we need to use span instead.
