### ISSUE TITLE
Hiding material/instruction page synchronization

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4833]
Hiding material/instruction page is not synchronized between quick action icons and edit panel.

If user hides page via material page quick action icon and then opens material page's edit panel, the icon indicating hide/show status in edit panel is not displaying the current state correctly.

Child of #4087

**Comment by onzag** [comment]
After quite a long checking, the materials are actually synchronized; there was an issue with the drafting that kept it forever, but overall what you are seeing is the fact that the draft is not the same as the actual material.

What we need is a label that indicates you are seeing a draft, everything in the content tab is part of the draft.

**Comment by onzag** [comment]
I now make draft go away after publish, but you will still have the same behaviour; while the main page causes the state to immediately change, the editor uses a draft.

**Comment by onzag** [comment]
Related to #4702
