### ISSUE TITLE
Workspace materials are missing enrollment notification for logged-in users

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4845]
When user that has sign-up permissions to the workspace but have not enrolled to the workspace, materials view does not show notification to the user.

![DeepinScreenshot_select-area_20191210122018](https://user-images.githubusercontent.com/3032883/70521608-2c1e4d00-1b48-11ea-972f-b0a28253f419.png)

Text: **plugin.workspace.materials.notSignedUpWarning**
Link: **plugin.workspace.materials.notSignedUpWarningLink**

Link should open workspace sign-up dialog

Child of #4087

**Comment by onzag** [comment]
This issue had been fixed before, this seems to be a clone.

**Comment by jjlankinen** [comment]
Not fixed, this is different one.
