### ISSUE TITLE
Workspace teachers panel is missing for non enrolled users

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4846]
If user has not enrolled to the course he/she is accessing, teachers panel should still be visible.

Currently teachers and announcements panels are both missing from non enrolled users. Only announcements should be hidden.

Child of #4087

**Comment by onzag** [comment]
The function to show the teachers is attached to the permission "WORSKPACE_LIST_WORKSPACE_MEMBERS" which the server specifies as "false", either this is not the right permission to use or the permission value is wrong.
