### ISSUE TITLE
New question to application form for "aineopiskelijat"

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#4864]
Sari Jaaranen: 

> Aineopiskelulomakkeen kolmanteen vaiheeseen "Hakemiseen tarvittavat lisätiedot" pitäisi lisätä seuraava pakollinen kysymys (voi valita vain yhden kohdan):

>Yleissivistävä koulutustausta
- Peruskoulu (tai vastaava)
- Lukion oppimäärä tai 4 vuotta lukio-opintoja
- En ole suorittanut mitään näistä

>Tästä tuleva tieto pitäisi tallentaa Pyramuksessa jo valmiina olevaan kenttään Koulutus/Ammatti

**Comment by pkukkon** [comment]
Moved to Pyramus issue 1079
