### ISSUE TITLE
Dropdown component's tooltip overflows mobile devices screen

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4956]
If select task field has example text added (which is shown in exercises after user checks exercise) the tooltip often renders outside of mobile devices viewport.

**Comment by jjlankinen** [comment]
Actually what you are showing in that screen shot is NOT an tooltip. It's only the example text. You can see the overlap of the tooltip when setting correct answer to the task field and then inputting long example text.

Example is only visible when task field does not have any correct answers set. Is correct answer is set then by answering incorrectly to the task field renders correct answer in the box that is greenish and places question mark after the correct answer text to function as an tooltip handler. Then tooltip contains the explanation data.

See the following screen shot:
![tooltip-overflow](https://user-images.githubusercontent.com/3032883/103893942-c7407800-50f6-11eb-8f79-433bde96741c.png)

**Comment by onzag** [comment]
Alright I see now will work on
