### ISSUE TITLE
Hyperlinks to material pages don't work reliably

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#4958]
Browsers seem to prevent/adjust users scroll position quite aggressively and our implementation currently don't work reliably when creating hyperlinks to single pages.

Desired behavior would be that when user click the hyperlink pointing to a single page in the middle of workspace materials the browser would scroll precisely to that position. Somehow basic anchors does work but at least Chrome has been reported to override those as well in the past.

Nevertheless we need to find some sort of solution to this as in production using the old tech this works 99% of times but in Redesign it seem to never work reliably.

**Comment by onzag** [comment]
This is because redesign renders mostly on the client side.

The only way to reliable solve this would be to use SSR or have single page tasks rather than the scrolling thing, or, on the other hand, not use native scrolling.

There's also the fact scrolling works differently when devtools are open.
