### ISSUE TITLE
Prefixing material URL links with baseUrl also modifies absolute links

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#4993]
If material page source has...

`<a href="/something/or/another">`

...it is an absolute link and should not be prefixed with baseUrl. The rendered result, however, is...

`<a href="/workspace/aaa/materials/section/page//something/or/another">`

Old code checking whether a link is absolute or not:

`var absolute = (src.indexOf('/') == 0) || (src.indexOf('mailto:') == 0) || (src.indexOf('data:') == 0) || (src.match("^(?:[a-zA-Z]+:)?\/\/"));`

If the source had...

`<a href="something/or/another">`

...then it would be a relative URL that should be prefixed (as the current implementation does).

**Comment by onzag** [comment]
4993-fixing-baselinks-in-a-and-iframe Fixed in there
