### ISSUE TITLE
Materiaalin näkyvyyden rajoituksen näkyminen editointitilassa

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#5020]
Materiaalin näkyvyyden rajoitus ei näy editointitilassa: ei sisällysluettelossa eikä sivun/osion kohdalla. Lisäksi editorissa materiaalin näkyvyyden rajoitus -painikkeen väri on hämäävä: voisi olla punainen, kun rajoitus on päällä, ks. kuva:

![image](https://user-images.githubusercontent.com/26649131/84028409-55098880-a999-11ea-8f99-2e8c99c9860d.png)

**Comment by jjlankinen** [comment]
Tästä keskusteltiin aikanaan että muutetaan toimimaan siten nämä ikoni painikkeet että vihreä kuvaa sitä että toiminto on päällä ja harmaa sitä että se ei ole päällä. Tällöin materiaalin näkyvyys toimii siten että kun painike on vihreä niin se on näkyvissä kaikille (eli pääsy on rajoittamaton) ja jos se on harmaa niin silloin on piilotettu kirjautumattomilta (eli rajattu pääsy). Tässä on siis muutettu mitä tämä painike loogisesti tekee, sillä ei enää vain rajoiteta näkyvyyttää vaan painike kertoo onko sivu näkyvissä vai ei.

Samalla logiikalla toimii silmä painike myös jolloin kun ikoni on vihreä niin se on näkyvissä ja harmaa ikoni kuvaa että sivu on piilotettu.

Tehtävän vastauksien näyttäminen toimii samaan tapaan eli kun ikoni on harmaana vastauksia ei näytetä ja vihreänä näytetään.

Yksi syy oli tähän muutokseen se että kaikki painikkeet noudattavat samaa logiikkaa, ja tällöin värit kuvaavat varmuudella tiettyä asiaa. Esim. punainen on vahvasti yhdistetty poistamiseen koko ympäristön läpi.

Voisi varmaankin miettiä olisko jokin muu tapa parempi kuvaamaan tätä erikois asetusta kuin ikoni.

**Comment by ninakurki** [comment]
Tämä taitaa olla ihan ok. Pidetään värilogiikka. Nyt ainakin adminit näkevät sisällysluettelossa kirjautumisen taakse rajattujen sisältöjen kohdalla ikonin. Siihen liittyy tosin bugi, josta teen erillisen issuen.
