### ISSUE TITLE
Tekstikentän leveys

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#5023]
Vaikka tekstikentille on asetettu sama leveys, ne ovat eri mittaisia. Alla olevien tekstikenttien leveys on 10. Tässä esimerkissä tekstikentät ovat taulukossa.
Löytyy ena1-kurssin kohtasta 4.8: https://otavanopisto.muikkuverkko.fi/workspace/ena1-kehittyva-kielitaito-tyoelamassa-toimiminen-ja-muita-muodollisia-tilanteita/materials#p-121459

![image](https://user-images.githubusercontent.com/26649131/84030941-88e6ad00-a99d-11ea-81b2-313a6780d0f1.png)

**Comment by jjlankinen** [comment]
Tämä luultavasti korjaantuu seuraavassa tuotanpäivityksessä.

Sen ainakin huomasin että tämä lyhyempi kenttä on määritetty kasvamaan kirjoittaessa (joka samalla sitten litistää taulukon muita kolumneja) ja tästä syystä leveys on hieman erilainen kuin ensimmäisessä kentässä koska yksi css määritys on virheellinen tässä tapauksessa.

**Comment by jjlankinen** [comment]
Otetaanpas komento takaisin. 

Meidän koodeissa näköjään laskettiin <Autogrow/> teksti kentälle erikseen leveys perustuen kentän koko asetukseen. Tämä leveys ei sitten laskettuna vastannut muiden kenttien leveyttä. 

Saadaan siis korjattua.
