### ISSUE TITLE
Sanan määritelmä

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#5036]
Sanan määritelmä ei näy muokkaustilassa.

**Comment by jjlankinen** [comment]
Tarkoitatko ettei tooltip tule esiin kun vie hiiren sanan määritelmän päälle vai jotain muuta?

Ainakin teksti johon on asetettu sanan määritelmä näkyy tyylillisesti oikein:
![word-definition](https://user-images.githubusercontent.com/3032883/84240514-cf0b5000-ab06-11ea-981f-a21e377bf630.png)

Itse tooltip:piä on luultavasti mahdotonta editoriin ladata mukaan.

**Comment by ninakurki** [comment]
Saila raportoi tän. Sanoi seuraavaa: mulla tulee sanan määritelmän kohdalle nuoliosoittimen vierelle kysymysmerkki ja ikkuna jossa on pitkä teksti, joka alkaa "Rikastekstieditori.....".

**Comment by ninakurki** [comment]
Kävin vielä itse toteamassa tilanteen ja tässä kuvakaappaus:
https://otavanopisto.muikkuverkko.fi/workspace/muikun-testiymparisto/materials#p-113768 -> Sanan määritelmä
![image](https://user-images.githubusercontent.com/26649131/84250104-498e9c80-ab14-11ea-93e7-31884cf6c756.png)

**Comment by jjlankinen** [comment]
Tämä rikastekstieditori teksti tulee aina kun vie hiiren kohdistimen editoriin. Ei liity sanan määritelmään.
