### ISSUE TITLE
Materiaalissa navigointi refressauksen jälkeen

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#5037]
Kun materiaaleissa on jossakin muussa kohtaa, kuin alussa ja näkymän päivittää (lataa uudelleen F5:sta), niin näkymä siirtyy materiaalien alkuun. Aktiivisena on sisällysluettelossa kuitenkin se kohta, jossa edellisellä kerralla oltiin. Tätä kohtaa ei voi klikata, koska se on jo aktiivisena. Hypätäkseen takaisin oikeaan kohtaan pitää klikata sisällysluettelosta ensin jostain muualta ja sitten sitä kohtaa johon haluaa mennä.

**Comment by jjlankinen** [comment]
Tähän liittyy issue #4958
