### ISSUE TITLE
Reordering material pages in desktop Chrome (83) is wonky

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#5050]
When trying to reorder material pages (and sections) by drag and dropping with mouse is nigh on impossible. Sometimes the dragged content seems to disappear completely, sometimes the drag is left on after the mouse button is released, and during the drag the console is flooded with Uncaught (in promise) crashes. Seems to work a lot more consistently in Firefox, for example.

**Comment by jjlankinen** [comment]
Related #4946
