### ISSUE TITLE
Enable pinch zoom on mobile

### ISSUE THREAD

**Issue by petja-laitila** [otavanopisto/muikku#5057]
Couple of reasons:
1. The text may be too small for the user to read.
  Consider the contrast issues with using a phone in sunlight, or the movement of riding a train, or just low vision.
2. The user may want to see more detail in an image. True on some physics courses for example.
  Especially with images that are scaled down to fit in the viewport
3. Selecting words to copy/paste may be easier for users when the text is larger.
4. The developer did a poor job of responsive design, and the user needs to zoom just to use the page.
 Muikku of course doesn't fall in this category, but still.
5. There is a browser bug or quirk (still a bug) that causes the default zoom level to be odd.
For example iOS9.
6. It can be confounding for users when a pinch/spread gesture is interpreted as something else.

**Comment by jjlankinen** [comment]
This is actually serious accessibility issue and setting maximum-scale to prevent zooming in mobile devices in meta tag is pure madness.
