### ISSUE TITLE
Muikku meets Accessibility Directive

### ISSUE THREAD

**Issue by sailakarjalainen** [otavanopisto/muikku#5079]
Make Muikku perceivable, operable, understandable and robust.
Requirements: level A & AA success criteria in [WCAG 2.1 Guidelines](https://www.saavutettavuusvaatimukset.fi/lait-ja-standardit/wcag-2-1/).

**Comment by jjlankinen** [comment]
Closing this as we don't need to keep this epic issue around as we use milestone for grouping accessibility directive related issues.
