### ISSUE TITLE
Label in name must be same as visually presented name

### ISSUE THREAD

**Issue by sailakarjalainen** [otavanopisto/muikku#5080]
Make sure that components with labels that include text or images of text have the same “accessible name” as the one presented visually.

Success Criterion: 2.5.3, level A ([FI](https://papunet.net/saavutettavuus/wcag-ohjeet/253-nimilappu-nimessa), [EN](https://www.w3.org/TR/WCAG21/#label-in-name))

**Comment by jjlankinen** [comment]
This is highly ambiguous as there does not seem to be definite list components provided which are not obeying this criteria.

Environment dialog (which is used to create a new communicator message) has been fixed as the criteria mentions form elements but other than that  it's very hard to grasp what to do.
