### ISSUE TITLE
Paikka ja toteutusmuoto saavutettavuusselosteelle

### ISSUE THREAD

**Issue by sailakarjalainen** [otavanopisto/muikku#5081]
Muikun saavutettavuusselosteelle on päätettävä paikka ja toteutusmuoto. 

Huomioitavaa:

- Selosteen on oltava saavutettavassa muodossa.
- Selostetta ylläpidetään: esim. tieto palvelun isoimmista päivityksistä ja saavutettavuusongelmien korjauksista
- “Paras tapa on, että luodaan selosteelle oma sivu, eli pitää seloste html:nä.” (saavutettavasti.fi)
- Pdf ei täysin kielletty, mutta ei myöskään suositeltava. 
- Pääsy selosteeseen on varmistettava eri käyttäjille: onko avoimen puolen etusivu riittävä, vai tarvitaanko linkkejä muualle? Tässä huomioitava esim. suoraan materiaaleihin tulevat käyttäjät, kirjautuneet käyttäjät, muuta kautta hakulomakkeeseen tulevat käyttäjät jne. Ratkaistava on myös, tehdäänkö hakemuksille oma seloste vai ei. 

Child of #5079

**Comment by sailakarjalainen** [comment]
Ninan ja Sailan ehdotus: 
- Seloste tehdään sellaiseksi, että Muikku ja hakusivusto ovat samassa. Selosteen tekstit on nyt lähes valmiit.
- Seloste on Google-dokkarissa, johon linkitetään muutamasta paikasta: Muikun avoimen puolen etusivun footerista ja hakusivuston footerista. Linkin tekstiksi tulee Saavutettavuusseloste. Lisäksi selosteeseen linkitetään Muikun ohjeet -työtilasta (Saila hoitaa tämän).

Eli tällä ehdotuksella toteutettavaksi jäisi ainoastaan linkit kummankin sivuston footeriin. Jos tällä mennään, niin teettekö oman issuen tarvittaessa hakusivustolle? Linkin kohteen saa Sailalta.

**Comment by jjlankinen** [comment]
Lisätään linkki tänne issuen kommentteihin. 

Alustavasti linkki laitettaisiin muikun avoimen puolen alapalkkiin. Jos tarvetta niin linkki laitetaan muuallekkin.

**Comment by sailakarjalainen** [comment]
https://docs.google.com/document/d/1EXS3TroGTNAq9N8bV1pK6W2byKntZpHudBHH3NBGgXY/edit?usp=sharing

**Comment by ninakurki** [comment]
Linkki: https://docs.google.com/document/d/1EXS3TroGTNAq9N8bV1pK6W2byKntZpHudBHH3NBGgXY/edit?usp=sharing
