### ISSUE TITLE
Lang-attribuutti jokaiselle sivulle

### ISSUE THREAD

**Issue by sailakarjalainen** [otavanopisto/muikku#5091]
Jokaisen verkkosivun kieli tulee olla määritetty. Yksinkertaisimmillaan määritys tehdään html-tagissa.

Huomioitavaa:
- Oletusarvoinen kieli on eri kuin käyttöliittymän kieli. Voiko oletusarvoiseksi kieleksi silti määritellä suomen, jos käyttöliittymä on englanninkielinen? 
- Kursseilla on eniten suomea, mutta esim. vieraiden kielten lukiokurssit sisältävät eniten opetettavaa kieltä.
- Oletusarvoisesta kielestä poikkeavat kielet luultavasti pitäisi myös määritellä, mutta tähän ei ole mahdollisuutta kaikkialla.

Onnistumiskriteeri: 3.1.1, taso A ([FI](http://papunet.net/saavutettavuus/wcag-ohjeet/311-sivun-kieli), [EN](https://www.w3.org/TR/WCAG21/#language-of-page))

**Comment by jjlankinen** [comment]
Avoin etusivu saa lang attribuutin valitusta lokaalista.

Kirjautunut etusivu ja ympäristö taso käyttää aina FI lokaalia lang attribuutissa.

Työtiloissa pitää voida asettaa oletus kieli ja sen lisäksi materiaalit ja ohjeet näkymien osalta pitää pystyä ylikirjoittamaan kieliversio.

Osioiden otsikoiden kieliversio pitäisi pystyä asettamaan osion muokkauksessa.

Materiaalisivujen kieliversio pitää pystyä asettamaan sivukohtaisesti joka vaikuttaa sivun otsikkoon ja sivun sisältöihin.
