### ISSUE TITLE
Lukemisjärjestyksen muuttaminen niin, että sisällysluettelo on ennen materiaaleja

### ISSUE THREAD

**Issue by sailakarjalainen** [otavanopisto/muikku#5092]
HTML-koodin kautta määrittyvän sisällön lukemisjärjestyksen tulee olla looginen ja intuitiivinen. CSS ei saa pakottaa järjestystä.

Loogista olisi, jos sisällysluettelo olisi ennen materiaaleja. 

Onnistumiskriteeri: 1.3.2, taso A ([FI](http://papunet.net/saavutettavuus/wcag-ohjeet/132-merkitykseen-vaikuttava-jarjestys), [EN](https://www.w3.org/TR/WCAG21/#meaningful-sequence))

Child of #5079

**Comment by jjlankinen** [comment]
Itse asiassa CSS pakottaa aina miten sivu piirretään selaimelle ellei selain tai käyttäjä erikseen poista CSS määrityksiä. Mikäli käyttäjä poistaa css määrityksen silloin html-koodissa esitetty järjrstys astuu voimaan.

Onko siis tarkoitus se että html:ssä on määritetty oikea looginen järjestys sivuston sisällöille ja sitten CSS muuttaa sen toimimaan kuten tällä hetkelläkin? Nykyisellään esim. sisällysluettelo piirretään ruudulle CSS:än ja javascriptin avulla materiaalien oikeaan laitaan.

**Comment by sailakarjalainen** [comment]
Joo, noin minä sen ymmärrän, että html:ssä pitäisi olla looginen järjestys sisällölle ja CSS:llä asetetaan visuaalisesti mielekkäällä tavalla. Eli oletan että nykytilasta pitää muuttaa se, että sisällysluettelo pitäisi olla html:ssä ennen materiaaleja, koska loogista on että ei-näkevä käyttäjä kohtaa ensin sisällysluettelon ja sitten vasta materiaalit. Näkevä käyttäjä kohtaa molemmat samaan aikaan.

Tuo "CSS ei saa pakottaa järjestystä" -kommentti oli kopioitu aiemmasta taulukosta, en ollut varma mitä sillä oltiin tarkoitettu. Katso täältä, jos se avautuu sieltä paremmin: https://docs.google.com/spreadsheets/d/1H4JMukh32v8XdMnIFmsDhfRJvDaecs__0143E-gLNgo/edit#gid=0
