### ISSUE TITLE
ckeditor unable to add link/image while evaluating

### ISSUE THREAD

**Issue by jarkkoh** [otavanopisto/muikku#510]
Fields not activated onclick. Strange behavior, works randomly.
win 8.1 chrome 45.0.2454.101
![unable_to_add](https://cloud.githubusercontent.com/assets/3033999/10452895/c0e69fa0-71b0-11e5-8361-b29e3390311e.gif)

**Comment by jarkkoh** [comment]
+ win 8.1 ie11

**Comment by jarkkoh** [comment]
Discussion area editor seems to be ok

**Comment by jjlankinen** [comment]
Tested using  Win8 with Chrome 47.0.2526.73 m and everything works fine. Next have to test it with Win8.1

**Comment by jjlankinen** [comment]
Tested usingnWin8.1 with Chrome 47.0.2526.73 m and everything works fine. Cannot repro this with virtual machine at least
