### ISSUE TITLE
Marginaalia h3:n ja h4:n yläpuolelle

### ISSUE THREAD

**Issue by sailakarjalainen** [otavanopisto/muikku#5120]
Sivun sisällä olevien alalukujen väliin halutaan yleensä enemmän tyhjää tilaa kuin mitä otsikkotyyli itsessään siihen nyt tuo. Tähän käytetään nykyään joko pakotettua rivinvaihtoa (kappaletekstistä tai seuraavasta otsikosta) tai tavallista rivinvaihtoa (esim. jos tilaa on saatava tyylilaatikon ja otsikon väliin). Tämän vuoksi aikaansaadun tyhjän tilan koko vaihtelee tai jos pakotettu rivinvaihto on tehty otsikosta, saavutettavuustarkistus valittaa tyhjästä header-tagista.

Olisiko mahdollista löytää h3:n ja h4:n ylle sopiva, nykyistä isompi marginaalimääritys, jotta jatkossa ei tarvitsisi kikkailla kappalevälien kanssa?

Huomiotava esim. seuraavat tilanteet:
- h3 - kappaletekstiä - h3
- kappaletekstiä - h3 - h4 - kappaletekstiä
- h3 - kappaletekstiä - h4 - kappaletekstiä

Huom. Se, että h2:n jälkeen tulisi suoraan h3 ja h4 ilman että välissä on kappaletekstiä, on tosi harvinaista (en muista nähneeni) ja muutenkin ei-toivottavaa tapaa rakennella materiaalia, Joten mielesetäni jos tämä case näyttää huonolta, niin ei haittaa.

**Comment by ninakurki** [comment]
Tästä juteltiin sisältötiimissä vähän aikaa sitten ja mietittiin, että voisiko marginaalin toteuttaa ylimääräisenä br-taginä, ei niinkään marginaalina, joka määritellään tyylitiedostona. Voisin kasata joitakin tämän kaltaisia issueita ja varata storytime-aikaa.
