### ISSUE TITLE
Valintakentän selitys näkyviin, jos käyttäjä vastaa oikein

### ISSUE THREAD

**Issue by sailakarjalainen** [otavanopisto/muikku#5221]
Harjoitustehtävissä tällä hetkellä valintakentän selitys tulee näkyviin vain, jos käyttäjä valitsee väärän vaihtoehdon.

Selitys voisi tulla näkyviin aina vastauksesta riippumatta siinä vaiheessa, kun tehtävä tarkistetaan.

**Comment by ninakurki** [comment]
Tässä oikea vastaus on siis kissa. Opiskelija näkee oikean vastauksen ja siihen liittyvän selityksen:
![image](https://user-images.githubusercontent.com/26649131/118449659-0ceffb80-b6fc-11eb-9cdd-fb8695752c02.png)

Tässä opiskelija on vastannut väärin eli koira. Kysymysmerkin takana oleva selityskään ei tule näkyviin:
![image](https://user-images.githubusercontent.com/26649131/118449852-390b7c80-b6fc-11eb-9a6e-d175eab973bf.png)
