### ISSUE TITLE
Workspace journal "SHOW ALL" does not work

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#5417]
When teacher or admin views students journal entries in Workspace Journal view's SHOW ALL selection in toolbar does not display any entries.

By default journal should load every students journal entries sorted by creation date (newest on top). 

View has infinity scroll so first fetch should display 10 entries made by workspace students and more will load after view is scrolled down.

When teacher or admin selects individual students entries from the drop down selection they load just fine.

**Comment by TeroOtavia** [comment]
Didn't find anything specific that could affect this in frontend. It seems that all filtering is happening in backend during fetch so problem could be laying there. All newer journal entries are load and showed correctly newest first in the list.

**Comment by jjlankinen** [comment]
After checking this seems to be non-issue and actually working as intended. Test case seemed to be based on student that was not active at the workspace in that time of testing.
