### ISSUE TITLE
Sticky search bar has gab with toolbar and content align incorrectly

### ISSUE THREAD

**Issue by TeroOtavia** [otavanopisto/muikku#5421]
![Näyttökuva 2021-04-07 112947](https://user-images.githubusercontent.com/81742464/113847863-8fea7180-97a0-11eb-8a75-6419796000f7.png)

**Comment by jjlankinen** [comment]
Issue is closed because currently this up coming fix would break logic with previously fixed scrolling issue in application-panel. They both use same properties to fix different thing different way that would collide together.
