### ISSUE TITLE
Opinnot: välilehtien näkyvyysongelma

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#5469]
Opinnot-näkymässä vasemmalla olevat nappulat/välilehdet häviävät välillä näkyvistä, kun näkymässä rullailee menemään:
![image](https://user-images.githubusercontent.com/26649131/116031424-4df97080-a666-11eb-9337-37210cea4592.png)

**Comment by jjlankinen** [comment]
Tämä korjaantui toisessa PR:ssä
