### ISSUE TITLE
Nullcheck for image (?) component

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#5477]
This is exactly not materials about materials, but the situation occurred in the workspace homepage description and likely involves the image-component.

1. A teacher was editing workspace description
2. She added an image and it looked wrong, so she deleted it and saved
3. Now the frontpage crashed, because of error "width is null"

Somehow the image src got mixed up or was unavailable and it crashed the workspace front page totally. 

There should at least be a nullcheck in place for this type of situation.

**Comment by TeroOtavia** [comment]
Cannot be reproduced. If problem starts again bother, we need to have more specific instruction to reproduce problem
