### ISSUE TITLE
Kirjautumisen taakse rajatut tehtävät

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#5519]
Materiaalin sisällysluettelossa näkyy (ainakin adminille) punainen maapalloikoni, jos ko. materiaali on rajattu näkymään vain kirjautuneille käyttäjille. Tämä toimii siis oikein. Jos harjoitustehtävän rajaa kirjautumisen taakse ja on itse mennyt testaamaan tehtävää, ko. ikoni ei näy. Onkohan tässä tila vain yhdelle ikonille? Ei voi siis näkyä kahta rinnakkain?

![image](https://user-images.githubusercontent.com/26649131/118448935-42481980-b6fb-11eb-92fd-9289a33b9428.png)

**Comment by jjlankinen** [comment]
Tämä rajausta kuvaava ikoni ei näy tosiaan kuin admin käyttäjille ja jos sellaiseen tehtävään vastaa silloin "vastattu" ikoni on korkeammalla prioriteetillä ja ainoastaan se näytetään.

Onko miten tarpeellista näkyä molemmat tiedot, kuvittelisin että näkyvyyttä rajaava tieto on admin käyttäjälle tärkeämpi materiaaleissa kuin se onko tehtävä tehty ja/tai arvioitu. Opiskelijoille tämä tilanne ei ole edes mahdollinen.

Voisi siis muuttaa toimimaan siten että näkyvyyden rajoitusta kuvaava ikoni olisi tärkeämpi ja korkeammalla prioriteetilla kuin tehtävän tekemistä kuvaava ikoni.

**Comment by ninakurki** [comment]
Totta. Riittäisi ehkä se näkyvyyttä rajoittava tieto. Se tehtävään vastaaminenhan on lähinnä testausta.
