### ISSUE TITLE
Muikun sisäinen leikepöytä ei toimi Materiaalit --> Ohjeet

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#5534]
Yritin kopioida Muikun materiaaleissa olevia sivuja Muikun sisäisen leikepöydän kautta saman kurssin Ohjeisiin. Ei onnistunut. Leikepöydälle leikkaaminen ikään kuin tuntui toimivan, mutta liittäminen ei tehnyt mitään.

**Comment by TeroOtavia** [comment]
Update:

- Materiaaleista/Ohjeista sivun kopioiminen ohjeisiin/materiaaleihin näyttäisi toimivan, mutta;
   - liitettäessä sivu menee aina oletuksena osion viimeiseksi eikä siihen väliin mihin se on haluttu
   - sivua päivittäessä asia on korjaantunut
   - sama pätee myös sisällysluettelossa
   
- Lisäksi;
   - Jos luo uuden sivun jo luotujen sivujen välille, sisällysluettelon mukaan sivu on viimeisenä listassa. 
   - sivun päivitys korjaa ongelman.
