### ISSUE TITLE
Perusopetuksen HOPS-lomake muikkuun

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#5589]
Suunnitellaan HOPS-lomake muikkuuun

HOPS-lomakkeen yhteyteen tulee laskuri, jolla opintoja voi suunnitella sekä viikkolukujärjestys jossa voi asettaa suunniteltuja tunteja viikolle.
HOPS-lomake näkyy opinnot-näkymässä sekä ot1-kurssilla

Tämän hetkinen HOPS-lomake

https://docs.google.com/document/d/1GO7pPnv279D8UzUrZu1CBu9i0LhY2-JGAi3pVSMQ1h0/edit

Laskuri prototyyppi:

https://avukkonen.github.io/laskuri/

HOPS-tietoa 

https://www.oph.fi/fi/koulutus-ja-tutkinnot/aikuisten-perusopetuksen-alkuvaiheen-ohjaus-ja-henkilokohtainen

Child of #5583

**Comment by ninakurki** [comment]
Nykyisen HOPS-lomakkeen muutosajatuksia: https://docs.google.com/document/d/1yM7FNk3EyJLJfpvQC0CjbDzSNiVGdmCQKhgT6LszG_o/edit
