### ISSUE TITLE
Tehtävän tallennuksen indikaattorin uudelleen sijoittaminen

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#5663]
Tällä hetkellä materiaalisivujen tehtävien tallennus indikaattori (tallennetaan, tallennettu, tallennus epäonnistunut) elementti sijoitetaan tehtäväkentän ylöpuolelle. Tämä aiheuttaa mahdollisia ongelmia tilanteissa joissa tehtävä on niin korkea ettei se mahdu sitä tehtäessä kokonaan käyttäjän ruudulle jolloin indikaattori katoaa ruudun ulkopuolelle. Mikäli näin käy tilanteessa jossa tehtävän tallennus on epäonnistunut, niin tällöin käyttäjä ei saa riittävää tietoa tästä ja on vaara että tehtävä vastaus katoaa jos/kun käyttäjä sulkee selaimen ennekuin on varmistanut tallentumisen onnistumisen.

Sijoitetaan tallennuksen tilaa kuvaava indikaattori ruudun vasempaan alareunaan ja mikäli tallennus epäonnistuu, indikaattorin lisäksi tehtäväkenttä jonka vastauksen tallennus epäonnistui visualisoidaan riittävän huomiota herättävällä ilmeellä.

**Comment by ninakurki** [comment]
Tämä tehty.
