### ISSUE TITLE
Incorrect message when browsing materials of a workspace to which you can sign up

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#5702]
If you browse materials of a workspace that you are not yet a student of, **but** you study in a line that **has** the right to sign up to that workspace, the `plugin.workspace.materials.cannotSignUpWarning` is incorrectly shown.

This feature broke because of recent backend changes. Before, that notification check was based on...

```
MUIKKU_PERMISSIONS.WORKSPACE_SIGNUP = #{sessionBackingBean.hasWorkspacePermission('WORKSPACE_SIGNUP')};
```

...in `core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-base.xhtml` which was used in `core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx` around line 517...

```
if (!state.status.permissions.WORKSPACE_SIGNUP)
```

The `WORKSPACE_SIGNUP` permission has since then been deprecated, so all references to it should be removed from the frontend and replaced with a REST call to...

`/coursepicker/workspaces/123/canSignup` (123 being the workspace entity id)

...which returns a boolean telling whether the student can sign up to that course or not.

**Comment by TeroOtavia** [comment]
Seems to be fixed already
