### ISSUE TITLE
Tehtäväkenttien oikean vastauksen tyyliuudistus

### ISSUE THREAD

**Issue by sailakarjalainen** [otavanopisto/muikku#5709]
Tehtäväkenttien oikean vastauksen (tai mallivastauksen) tyyli pitää uudistaa. Katsottava ainakin fontin koko ja muotoilu (kursivointi pois) sekä taustaväri. Lisäksi voisi katsoa, voisiko vaihtoehtoiset oikeat vastaukset erotella toisistaan selkeämmin. 

Koskee valintakenttää, tekstikenttää, muistiokenttää ja järjestelykenttää. 

Tässä tyylissä ja tulevassa tehtäväpalautteessa (#5594) voisi olla visuaalisesti jotakin samaa.

**Comment by ninakurki** [comment]
Tehty tyyliuudistuksen yhteydessä.
