### ISSUE TITLE
Arviointi-näkymän tyylit: taulukot

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#5764]
Arviointi-näkymässä oleva materiaali piirtyy eri tavalla kuin materiaaleissa. Esimerkiksi taulukoista voi tulla lähes lukukelvottomia. Opettaja Nelli Raivio raportoi ongelmasta, joka on hänen mukaansa uusi. Uudella YH1-opintojaksolla tehtävässä 5.11. taulukko materiaaleissa näyttää tältä:
![image](https://user-images.githubusercontent.com/26649131/135089227-4867a447-bfb1-4434-b6a0-e413bbf1ab0a.png)

Ja arvioinnissa se näyttää tältä ja sitä on vaikea lukea, koska soluissa tavara on väärässä kohdassa solua:
![image](https://user-images.githubusercontent.com/26649131/135088874-90750c36-8c6e-4fc0-810e-517397c8b29d.png)

Arviointi-näkymän taulukot vaativat siis UI-hifistelyä.

**Comment by jjlankinen** [comment]
Korjaantunut uudssa arvioinnissa.
