### ISSUE TITLE
Rivittyvän vaakasuuntaisen järjestelykentän vastaus ei pysy paikoillaan

### ISSUE THREAD

**Issue by sailakarjalainen** [otavanopisto/muikku#5767]
Jos vaakasuuntainen järjestelykenttä on niin pitkä, että se rivittyy esim. kahdelle riville, tehtävän vastaus ei näytä pysyvän paikoillaan.

HUOM!
Ongelmat esiintyvät vasta kun raahaamisen sijaan järjestää sanat hiirellä klikkaamalla. Tämä ei myöskään laukaise tehtävän tallennusta tällä hetkellä.

Eli tässä tehtävä on palautettu:
![järjestely1](https://user-images.githubusercontent.com/69461897/135270188-3aa88c92-b29e-4118-adc9-cb740c7fc7b2.png)
 
Ja tässä selain on päivitetty ja tehtävää menty tarkastelemaan uudelleen. Tehtävä on pysynyt palautettu-tilassa ja muiden kenttien vastaukset ovat pysyneet paikoillaan (muut mahtuvat yhdelle riville).
![järjestely2](https://user-images.githubusercontent.com/69461897/135270568-26267011-5d98-437b-b2e6-8691e0b7fb9d.png)

Lisäksi tehtävään on melko vaikea vastata, jos kenttä rivittyy.

**Comment by jjlankinen** [comment]
Saisko tästä jonkinlaisen demon tai vaikka url:in missä tämän voi toistaa. En saa ongelmaa toistettua omalla koneella Firefox:lla.

**Comment by sailakarjalainen** [comment]
Nuo kuvakaappaukset on täältä, kohdasta 8.3, 3. virke: https://otavanopisto.muikkuverkko.fi/workspace/ena2-englanti-globaalina-kielena/materials#p-237235

Ja Chromea käytetty.

**Comment by jjlankinen** [comment]
Hmm, Firefox:la ja Chrome:lla järjestys kyllä pysyy paikallaan kun siihen on vastattu.

Vastaamisessa usean rivin järjestelykentässä kannattaa huomioida että raahattava sana korvaa raahauksesas aina toisen sanan jonka päälle sitä koittaa raahata. Ne siis vaihtavat paikkaa aina keskenään.

**Comment by sailakarjalainen** [comment]
Pysyykö vastaukset paikoillaan, vaikka päivittää selainnäkymän tehtävän palauttamisen jälkeen?
