### ISSUE TITLE
Guider search field issue

### ISSUE THREAD

**Issue by petja-laitila** [otavanopisto/muikku#5779]
Steps to reproduce.
1. In guider search with a name
2. Go to any of the searched  students guider page
3. Click on the icon that takes you back to guider main page
4. See that the search field is now empty, but query string is still present in the url. Guider now shows previous search results with empty search bar.

**Comment by TeroOtavia** [comment]
Update. Can't reproduce bug as described but if refreshing page at one students information page AND then returning to student list will search field loose query string even though its still present in the url.
