### ISSUE TITLE
google oauth login tilakoodi:1000

### ISSUE THREAD

**Issue by jarkkoh** [otavanopisto/muikku#579]
Unable to login muikku.staging.fi using admin rights: jarkko.hakanen@otavanopisto.fi. Cache cleared and no other sessions backround.

**Comment by jarkkoh** [comment]
otavanopisto.muikkuverkko.fi ok. Affects only staging.

**Comment by ilmoeuro** [comment]
A better error code would be in order

**Comment by ilmoeuro** [comment]
Move to otavanopisto/pyramus
