### ISSUE TITLE
Error- publishing the workspace 

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#582]
User describes:

>Maanantaina tosiaan on terveystiedon ryhmäkurssi starttaamassa ja kaikki on muutoin ok, mutta kun yritän kurssin etusivulla painaa "julkaise" niin saan jatkuvasti vain error-viestiä. Näkyykö kurssi kuitenkin normaalisti opiskelijoille, jotka kurssille on liitetty eli voinko vain jättää tämän asian  huomiotta...?

>Sain ongelmaa nyt ratkottua sen verran, että Firefoxista Exploreriin vaihtamalla onnistuin kurssin etusivulla painamaan julkaise-nappia. Explorerilla ei kuitenkaan ainakaan tällä hetkellä näytä onnistuvan ohjeiden ja etusivun muokkaus (tai lähinnä muokkauksen julkaiseminen), joka aiemmin parisen viikkoa sitten toimi ainakin Firefoxilla ok. Mutta tämän kanssa ei sinänsä ole akuuttia hätää, oleelliset tiedot etusivulla ja ohjeissa ovat ok

**Comment by pkukkon** [comment]
Merged to devel.
