### ISSUE TITLE
Nettilukion hakulomake

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#6027]
Nettilukion hakulomake:

Sivu 1 --> ei muutoksia

Sivu 2 --> 

VAIHDETAAN RASTITUSLISTAKSI, KOSKA PITÄÄ PYSTYÄ VALITSEMAAN USEITA VAIHTOEHTOJA:
Aiemmat opinnot*
Voit valita useamman vaihtoehdon.

Lista säilyy muuten ennallaan, mutta 
Ammatillinen 2. aste --> tilalle uudet kohdat:
Ammatilliset 2. asteen opinnot (keskeytynyt)
Ammatilliset 2. asteen opinnot (valmis tutkinto)

Kerro tarkemmin -tekstikenttä näkyvillä koko ajan. Nyt tulee näkyviin vasta kun valitsee Muu.

Näiden alle kolme uutta, kaikille näkyvää kysymystä:
Minä vuonna olet valmistunut peruskoulusta?*
--> avoin vastauskenttä (pakollinen), johon voi kirjoittaa myös tekstiä (eikä pelkkää vuosilukua)

Missä oppilaitoksissa olet ollut kirjoilla peruskoulun jälkeen?*
-> avoin tekstikenttä (pakollinen)

Missä oppilaitoksessa olet viimeksi opiskellut ja milloin?*
--> avoin tekstikenttä (pakollinen)

POIS: Aiemmat opinnot -> Lukio (keskeytynyt) -valinnasta tulevat kentät: Oppilaitos JA Opintojen kesto

VALINTA: Aiemmat opinnot --> Lukio (keskeytynyt)
--> Oletko suorittanut aiemmin yo-kokeita?* --> Kyllä, En
Lisätietoteksti: Huomioi, että yo-kokeita koskevat tiedot eivät siirry automaattisesti koululta toiselle. Jos olet ilmoittautunut ylioppilaskokeisiin tai suorittanut jo joitain kokeita, ilmoita tästä jo hakuvaiheessa.
JA TOINEN KYSYMYS
--> Aiempien lukio-opintojen kesto --> LYHYT TEKSTIKENTTÄ

ENNALLAAN: Opiskelen tällä hetkellä toisessa oppilaitoksessa*
ENNALLAAN: Opiskelutavoitteet*
ENNALLAAN: Olen tällä hetkellä*

Haluan kertoa itsestäni ja opiskelutavoitteistani seuraavaa
TILALLE: Haluan kertoa Nettilukion omalle ohjaajalle nämä taustatiedot
Voit kertoa esimerkiksi opiskeluvalmiuksistasi, ajankäytöstäsi, motivaatiostasi ja tavoitteistasi. Nämä tiedot välitetään omalle ohjaajallesi, kun aloitat Nettilukion opinnot.

******

ALAIKÄISTEN SIVU 2:	
Huoltajan tiedot

Huoltajan tiedot -otsikon alle tarkenne: Merkitse alaikäisen hakijan kaikkien virallisten huoltajien tiedot.

Ensimmäinen kohta voisi olla pakollinen ja siinä “huoltaja 1”. Sitten voisi olla samat kohdat vielä kahteen kertaan, mutta ei pakollisena “huoltaja 2” ja “huoltaja 3” -> mahdollisuus täyttää myös nämä kentät, mutta ei tarvitsisi.

Sivun loppuun vielä kysymys ja tekstikenttä (vapaaehtoinen): Jos huoltajia on useampi, kehen ollaan ensisijaisesti yhteydessä nuoren opiskeluasioissa?

**Comment by pkukkon** [comment]
Siirretty Pyramukseen.
