### ISSUE TITLE
Nettiperuskoulun hakemuksen muutokset

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#6028]
Nettiperuskoulun lomake

TEKSTIMUUTOKSIA
Olet hakemassa Nettiperuskouluun
Nettiperuskoulussa voit opiskella kesken jääneen peruskoulun loppuun tai tehdä koko aikuisten perusopetuksen oppimäärän alusta asti. Nettiperuskoulu on tarkoitettu yli 17-vuotiaille opiskelijoille, joilta puuttuu perusopetuksen päättötodistus.
--> TÄMÄ TEKSTI NÄYTTÄÄ OLEVAN AINA HAKEMUKSEN YLÄLAIDASSA

**********

Hakemuksen liitteet -sivu

TEKSTIMUUTOS:
Huom! Onnistuneesti lähetetystä hakemuksesta saat sähköpostiviestin. Viestissä olevan linkin ja tunnuksen avulla voit muokata hakemusta siihen asti kunnes se otetaan käsittelyyn. Voit myös lisätä liitteitä.
--> Huom! Onnistuneesti lähetetystä hakemuksesta saat sähköpostiviestin. Viestissä olevan linkin ja tunnuksen avulla voit muokata hakemusta. Voit myös lisätä liitteitä.

TEKSTIMUUTOS:
Voit toimittaa todistusjäljennökset myös postitse (Mikkelin kaupungin liikelaitos Otavia / Nettiperuskoulu, Otavantie 2 B, 50670 Otava)
--> Voit toimittaa todistusjäljennökset myös salatulla sähköpostilla (saat tiedot hakemuksen käsittelijältä).

****************

HAKEMUSTEN KUITTAUS:
Kun kuittaa hakemuksen, sen jälkeen kaikki heräteviestit hakemuksen liitteiden lisäyksestä tulevat ainoastaan hakemuksen kuitanneelle henkilölle. Tämä voi olla haaste loma-aikana/poissaoloaikana, kun tieto esim. todistusten lisäyksestä tavoittaa ainoastaan poissaolijan. Tähän pitäisi ehkä olla mahdollisuus valita herätteiden saaja?

**Comment by pkukkon** [comment]
Siirretty Pyramukseen.
