### ISSUE TITLE
Materiaali täydennys palaute ja tehtävän peruutus

### ISSUE THREAD

**Issue by TeroOtavia** [otavanopisto/muikku#6120]
Jos ope arvioi tehtävän Täydennettäväksi ja laittaa tehtävään palautetta, palaute katoaa, kun opiskelija peruu tehtävän palautuksen. Eikös tää ole jossain vaiheessa toiminut kuitenkin niin, että opettajan palaute ei katoa siinä yhteydessä?

Alla olevassa kuvassa siis oli Täydennettävä-merkintä ja palaute, mutta ne katosivat. Tämä ei varsin ehkä liitty vain yhdistelmäopintojaksoihin. 

<img width="374" alt="bug" src="https://user-images.githubusercontent.com/81742464/168532514-5c52119f-f6bc-4e2d-8d0e-30444bfbea69.png">

**Comment by avukkonen** [comment]
Nonissue, toimii oikein
