### ISSUE TITLE
Ohjaaja- ja opiskelijalistat chattiin näkyviin toisilleen

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#6261]
Mietitään, minkälaisia issueita asiasta voi luoda.

- Opiskelijalle lista omista ohjaajista, joilla chat on päällä
- Ohjaajalle lista omien ohjausryhmien opiskelijoista, joilla on chat päällä (ohjausryhmittäin).
- Ylipäätään tapa listata ihmisiä, joihin sinulla on joku suhde (opettajasi, opiskeijasi, ohjaajasi, kaverisi)

```
 {
  userEntityId: number,
  id: string,
  nick?: string,
  name?: string,
}
```

### Käyttäjätarina - Ohjaaja
Kun ohjaaja asettaa chatin päälle, hänelle näkyy ihmiset-välilehdellä ohjausryhmiä. Ohjausryhmiä klikkaamalla hän saa auki listan sen ohjausryhmän opiskelijoista, joilla on chat asetettu päälle. Opiskelijan nimeä klikkaamaalla aukeaa yksityisviesti-chat opiskelijan kanssa.

### Käyttäjätarina - Opiskelija
Kun opiskelija asettaa chatin päälle, hänelle näkyy ihmiset-välilehdellä lista ohjaajista. Ohjaajan nimeä klikkaamaalla aukeaa yksityisviesti-chat ohjaajan kanssa.

**Comment by pkukkon** [comment]
Closed due to new chat in development.
