### ISSUE TITLE
@types/shared tiedoston any - arvoille voisi tehdä jotain

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#6372]
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/shared.ts

Joko piilottaa ne lintiltä tai laittaa niihin jotain muuta

**Comment by TeroOtavia** [comment]
Properties that can be fixed by changing type other than value are already changed. Otherwise disabling eslint error fixes linting warning from these and it has been done also.
