### ISSUE TITLE
Tehtäviä ei ole mahdollista muuttaa takaisin teoriasivuiksi

### ISSUE THREAD

**Issue by sailakarjalainen** [otavanopisto/muikku#6392]
Jos materiaaleissa sivusta on tehty harjoitustehtävä, arvioitava tehtävä tai oppimispäiväkirjatehtävä, sitä ei ole mahdollista muuttaa enää ns. teoriasivuksi, koska sitä ei ole alaspudotusvalikossa.

Yleensä näistä sivuista puhutaan "teoriasivuina", ja tämä nimi voi näkyä sisällöntuottajille, vaikka opiskelijoille ei puhuta sivuista. Nimi voi olla myös pelkästään "Teoria".

**Comment by jjlankinen** [comment]
Sen sivun voi muuttaa teoriasivuksi klikkaamalla aktiivista valikon sivutyyppiä. Tämä deaktivoi sen sivutyypin jolloin siitä tulee teoriasivu.

**Comment by pkukkon** [comment]
Olisiko käytettävämpi tai intuitiivisempi lisätä siihen sivuvalikkoon ekaksi harmaalla ikonilla juurikin tuo teoriasivu. Itsekin hämmennyin nykyisestä toteutuksesta.

**Comment by jjlankinen** [comment]
Olisi vamasti, samalla voisi sen valikon sulkea automaagisesti kun klikkaa sivua niin ei tarvitse turhaan erillistä klikkausta tehdä sulkeakseen sen valikon.

**Comment by pkukkon** [comment]
Jep, toimisi sitten ihan kuin tavan popup. Poistin bugimerkinnän, toteutetaan ominaisuusmuutoksena.
