### ISSUE TITLE
Error kuvan latauksessa

### ISSUE THREAD

**Issue by sailakarjalainen** [otavanopisto/muikku#6425]
Satunnaisesti, kun materiaalieditoriin yrittää ladata kuvaa, tulee kuvan mukainen error-ilmoitus ja kuva ei lataudu ko. sivulle.

![kuvaerror](https://user-images.githubusercontent.com/69461897/208062702-f89358a1-caa4-4f18-bd89-58af9b947114.png)

![kuvaerror2](https://user-images.githubusercontent.com/69461897/208062748-4906aa49-9617-4ecf-899f-fcf880a98405.png)

Jos sivulla tulee yhden kerran tällainen ilmoitus, kuvan lataaminen ei jatkossakaan onnistu samalle sivulle, vaan sivusta pitää tehdä kopio, jolle kuva latautuu oikein.

**Comment by pkukkon** [comment]
Fixed via #6916
