### ISSUE TITLE
Täydennettäväksi arvioitavaan tehtävään ei voi antaa suullista palautetta

### ISSUE THREAD

**Issue by sailakarjalainen** [otavanopisto/muikku#6428]
Jos opettaja äänittää arvioitavaan tehtävään suullisen palautteen ja valitsee Arviointi-kohtaan sen jälkeen "täydennettävä", äänitystyökalu katoaa eikä palaute tallennu.

Myös täydennettäväksi arvioituihin tehtäviin pitäisi voida antaa suullista palautetta. Jos tälle on tällä hetkellä jokin tekninen este (esim. arviointihistoriaan liittyäv), niin toteutuksen pitäisi olla esim. sellainen, että äänitystyökalu on näkyvissä vain kun Arviointi-kohtaan on valittu arvosana.

**Comment by sailakarjalainen** [comment]
Liittyykö tämä tähän jotenkin: https://github.com/otavanopisto/muikku/issues/6120

**Comment by TeroOtavia** [comment]
Täydennettäville tehtäville ei ole vielä suullisen palautteen tukea. Ominaisuuden tekemisestä on tehty kylläkin issue. Toteutusaikataulu ei vielä tiedossa.

**Comment by sailakarjalainen** [comment]
Ok, en löytänyt tuota aiempaa issueta. Suljen tämän.
