### ISSUE TITLE
Oppimispäiväkirjatehtävä: pikkufiksejä

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#6441]
1. Oppimispäiväkirjan muistiokentän oletuskorkeus on hiukan isompi nyt kuin tavallisella muistiokentällä, jossa on editori. Yhdenmukaistetaan kenttien korkeus siten, että se on sama kuin editorillisella muistiokentällä.

2. Luonnos-tilassa olevan oppimispäiväkirjamerkinnän luonnos-teksti näkyy arvioinnissa väärin. Demolla se on kiinni otsikossa, kehitysympäristössä se on värillisellä taustalla, mutta teksti on otsikon kanssa eri rivillä ja tausta on venähtänyt koko rivin pituiseksi. Vaatii fiksausta.

3. Sekä oppimispäiväkirjassa että arvioinnissa uusin merkintä on nyt ylimmäisenä. Oletusjärjestys voisi olla molemmissa toisin päin eli ensimmäinen eli vanhin ylimmäiseksi. Järjestyksen vaihto voisi olla jees, oletuksena vanhin ekana, mutta voisi kääntää järjestyksen myös toisinpäin eli uusimman ylimmäksi.

**Comment by TeroOtavia** [comment]
Kohta 2. korjataan branchissa #6333
