### ISSUE TITLE
Chatin testaushuomioita

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#6450]
- opiskelijalle ei saa päälle chattia, mutta se toimii, jos oli jo valmiiksi päällä (Omat tiedot -> Chat-asetukset)
- chatissa manuaalisen status-värin vaihtaminen ei näy opiskelijalle --> jos väri ei vaihdu, sen voisi ottaa pois kokonaan/piilottaa ja odotetaan Viljakaisen status-viritystä
-- kun kirjauduin opiskelijana ulos ja sisään, open status näkyi harmaana (vaikka se oli oikeasti punainen). Kun ohjaaja vastasi opiskelijan viestiin, pallero muuttui vihreäksi --> jotenkin oudosti toimii se siis
- jos ohjaaja sulkee opiskelijan kanssa käymänsä keskustelun ja opiskelija ei kirjoita jotain, ohjaaja ei pääse takaisin keskusteluun (tämä korjautunee ainakin sitten, kun omat ohjattavat alkavat listautua ohjaajalle)

**Comment by jjlankinen** [comment]
Ei korjata vaan otetaan huomioon kun chat uudestaan otetaan tulille.
