### ISSUE TITLE
Sisäänkirjautuneen käyttäjän rooli

### ISSUE THREAD

**Issue by pkukkon** [otavanopisto/muikku#6470]
Varsin monessa paikassa backend-koodia ollaan kiinnostuneita sisäänkirjautuneen käyttäjän roolista. Olisi varsin luontevaa, että tuon tiedon voisi onkia suoraan SessionControllerilta.

**Comment by aviljakaine** [comment]
Moniroolitus muuttaa roolimekanismia hieman, tätä voisi evaluoida sen jälkeen uudelleen.

**Comment by aviljakaine** [comment]
SessionControllerissa on nyt hasRole yllämainitun PR:n myötä. Avataan tämä uudelleen, jos tarvetta.
