### ISSUE TITLE
Keskustelun herätteessä väärä viesti

### ISSUE THREAD

**Issue by sailakarjalainen** [otavanopisto/muikku#6523]
Jos on tilannut keskustelun tai keskustelualueen ja sihen tulee vastaus aiempaan viestiin, herätteessä näkyy keskustelualueen aloittava viesti, mutta viestin lähettäjänä näkyy sen henkilön nimi, joka on kirjoittanut vastauksen. Näin ei varmaankaan ole tarkotus olla?

**Comment by ninakurki** [comment]
En tiedä onko kyse tästä samasta ongelmasta, mutta käytännössä jos

- tilaa keskustelun
- keskustelun yhteen ketjuun tulee uusi viesti
- heräteviestissä on ketjun eka viesti, ei sitä uutta viestiä

![image](https://user-images.githubusercontent.com/26649131/233047532-29e69a7e-dfec-47a3-a57d-fa943f9cdfd9.png)

Jos kyse on eri ongelmasta, tästä voisi tehdä oman issuen.

**Comment by sailakarjalainen** [comment]
Juuri tästä samasta oli kyse tuossa alkuperäisessä.
