### ISSUE TITLE
Välipalautepyynnöt jäävät arviointipyyntöihin

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#6579]
Opettaja ilmoitti ongelmasta, että välipalautepyynnöt jäävät killumaan arviointipyyntöihin, vaikka välipalaute on annettu. Arviointipyynnöt-näkymässä olisi hyvä näkyä vain ne tapaukset, jotka on opettajalta tekemältä.

Jos tarvitsee lisätietoja, minulta saa tietoon opettajan nimen.

**Comment by pkukkon** [comment]
User error :)
