### ISSUE TITLE
Recording audio to Muikku

### ISSUE THREAD

**Issue by anttileppa** [otavanopisto/muikku#659]
As a student I would like to use record voice to a Muikku assingment. 
As a teacher I would like to have assingment type where student needs to record his/her voice to Muikku.

**Comment by issakainen** [comment]
Here is a list _IDEAS_ that came up when the issues was groomed: 

- Student starts by pressing a record button. This starts a small countdown timer "3...2...1...go"
- Ability to pause and stop recording
- If student presses stop and after that record it starts a new recording without deleting the previous one.
- Student has the ability to create multiple recordings, delete recordings and listen them.
- User can rename files ie "Vastaus tehtävään 1". Default filename is date+time.
- Teacher has a mediaplayer that has ability to play, pause, stop, rewind/forward and go to a specific moment.
