### ISSUE TITLE
Ohjaajien lataus kaatuu, jos opiskelija on lopettanut opinnot

### ISSUE THREAD

**Issue by aviljakaine** [otavanopisto/muikku#6599]
Opiskelija, joka on lopettanut opinnot, voi mennä katsomaan omia suorituksiaan, mutta Opinnot-sivulla olevien ohjaajien lataaminen epäonnistuu tässä yhteydessä. Pitäisikö ohjaajien näkyä tässä näkymässä opintojen päätyttyä eli pitäisikö lataus korjata vai poistaa ohjaajat näkymästä?

![image](https://github.com/otavanopisto/muikku/assets/85352883/82d20a15-0d1d-4435-b77e-c66205731ac5)

**Comment by jjlankinen** [comment]
Onko sillä merkitystä opiskleijalle ketkä hänen ohjaajansa ovat olleet? Jos on niin tällöin ohjaajat pitäis näkyä.

Mikäli ohjaaja tieto on turha opintonsa päättäneille niin koko ohjaajasi kohta voidaan piilottaa tällöin.

**Comment by ninakurki** [comment]
Joo, mun mielestä ohjaajan ei tarvii tuossa vaiheessa enää näkyä.
