### ISSUE TITLE
Poistetaan vanhat lokaalit lopullisesti

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#6687]
Vaikka uudet lokaalit ovat jo linjoilla, vanhat lokaalitiedostot ovat vielä olemassa javapuolella. Ne voisi poistaa lopullisesti.

**Comment by aviljakaine** [comment]
Poistettavia siis `xxxJsPluginMessages_xx.properties` -tiedostot ja viittaukset näihin `PluginDescriptor`eista

**Comment by pkukkon** [comment]
Kyytiä saanee samalla myös (ainakin) `JavaScriptLocaleServlet` ja `LocaleLocation`

**Comment by pkukkon** [comment]
Will be addressed via #6723
