### ISSUE TITLE
WCAG 2.1.1: Modaalidialogiin ei saa näppäinkohdistinta

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#6814]
**Kriittinen ongelma**
2.1.1: Ei täyty

Kun käyttäjä painaa Ilmoittaudu linkkiä, avautuu modaalinen dialogi. Modaaliin ei saa kuitenkaan näppäinkohdistinta, vaan modaali sulkeutuu, kun käyttäjä painaa sarkainta. Ruudunlukija- ja näppäimistökäyttäjät eivät siis pysty lainkaan ilmoittautumaan modaalin
kautta.

**Korjausehdotus:** Kun näkymään avautuu modaalinen dialogi, kohdistin tulee viedä suoraan siihen. Tässä tapauksessa kohdistus kannattaa olla ”Kurssille ilmoittautuminen” otsikossa (Tabindex=”-1”). Modaali tulee olla suljettu tila, josta kohdistin ei pääse karkaamaan, ennen kuin käyttäjä on sulkenut modaalin. Huolehdittava, että kaikki modaalin komponentit ovat myös näppäimistöhallittavia, ja että sulkemispainikkeella (x) on saavutettava nimi ja rooli (aria-label=”sulje”).

**Kognitiivinen saavutettavuus:** ”Viesti työtilan opettajalle” vaikuttaa näkymän ainoana syötekenttänä pakolliselta tiedolta. Nimilapun perään voisikin lisätä esimerkiksi (valinnainen). Lisäksi termin ”työtila” sijaan tulee käyttää muissakin yhteyksissä käytettyä termiä ”kurssi”.

**Comment by TeroOtavia** [comment]
Ilmoittautumis dialogi/modaali on näppäimistösaavutettava ja focus ei pääse karkaamaan siitä tai dialogi ei pääse enää sulkeutumaan. Toteutettu aikaisempien pr:ien yhteydessä osana toista kokonaisuutta.
