### ISSUE TITLE
WCAG 2.1.1.: Modaalidialogiin ei saa näppäinkohdistinta

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#6834]
**Kriittinen ongelma**
2.1.1: ei täyty

Kun käyttäjä painaa Tehtävät-linkkiä, avautuu modaalinen dialogi. Modaaliin ei saa kuitenkaan näppäinkohdistinta, vaan modaali sulkeutuu, kun käyttäjä painaa sarkainta. Ruudunlukija- ja näppäimistökäyttäjät eivät siis pysty lainkaan tarkastelemaan tehtävien merkintöjä modaalin kautta.

**Korjausehdotus:** Kun näkymään avautuu modaalinen dialogi, kohdistin tulee viedä suoraan siihen. Tässä tapauksessa kohdistus kannattaa viedä modaalin otsikkoon (Tabindex=”-1”). Modaali tulee olla suljettu tila, josta kohdistin ei pääse karkaamaan, ennen kuin käyttäjä on sulkenut modaalin. Huolehdittava, että kaikki modaalin komponentit ovat myös näppäimistöhallittavia, ja että sulkemispainikkeella (x) on saavutettava nimi ja rooli (aria-label=”sulje”).

**Kognitiivinen saavutettavuus:** Tehtävät-painike ei viesti kaikesta tiedosta, jota sen takaa löytyy. Aukeavan modaalidialogin tiedot eri välilehtineen tulisi esittää helpommin havaittavasti jo varsinaisessa käyttöliittymässä Suoritukset-välilehdellä.

**Comment by TeroOtavia** [comment]
Opinnot->Suoritukset->Tehtävät dialogin/modaalin saavutettavuus korjaukset on tehty.
