### ISSUE TITLE
WCAG 1.3.1: Mathjax

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#6870]
**Kriittinen ongelma**
1.3.1: ei täyty

Esimerkiksi Kemian tehtävissä on käytetty valintaruutuja joiden sisältö on tuotu MathJax palvelulla. Sisällön oletusasetukset ovat sellaiset, että ruudunlukija ei lue lainkaan vaihtoehtoja, eli matemaattisia merkkejä. Tehtävä on siis täysin epäsaavutettava ruudunlukijalla. Yllättäen alueesta on kuitenkin mahdollista avata (ilmeisesti vain hiiren oikealla, ei toiminut shift + f10)
lisävalintoja, joilla mm. saavutettavuuden saa korjattu. Eli kun valikosta valitsee Accessibility -> Explorer -> Active, niin ruudunlukija lukee myös vaihtoehtojen sisällöt. Ongelma on, että ainakaan testatessa näppäimistöllä ja ruudunlukijalla asetusnäkymää ei onnistuttu avaamaan, vaan asetukset saatiin esiin vain hiirellä.

**Korjausehdotus:** Kannattaa selvittää, saako MathJax palvelun sisältöihin oletusasetukseksi saavutettavuusominaisuudet päälle, jolloin sisältö olisi myös ruudunlukijalla saavutettava.

**Comment by jjlankinen** [comment]
MathJax dokumentaatio kertoo että kyseisen Accessibility valikon saa auki kun kaava on kodistettuna tabulaattorin avulla ja painaa shift + space näppäinyhdistelmään. Tämän jälkeen valikossa pääsee liikkumaan nuolinäppäimillä ja valinnat tehdään enter painikkeella.

Lisää miten Accessibvility laajennos toimii MathJax:ssa voi lukea täältä: https://mathjax.github.io/MathJax-a11y/docs/
