### ISSUE TITLE
Kurssin tuottajien nimet vaihtelevat listassa paikkaa

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#6932]
Kurssin tuottajat vaihtavat mystisesti paikkaa, vaikka itse yrittäisi laittaa ne tiettyyn järjestykseen. Toiveena siis on, että nimet pysyisivät asetetussa järjestyksessä. Kyse on kurssin etusivusta.

Tässä alla olevassa esimerkissä alkuperäinen järjestys oli tämä ja kuvassa järjestys sen jälkeen, kun selainnäkymää oli päivitetty:
Johanna Mattila, Otavian sisältötiimi, Satu Tuomela, Päivi Korhonen, Heikki Koponen, Juha Hannikainen, Jenni Hildén

<img width="605" alt="image (2)" src="https://github.com/otavanopisto/muikku/assets/26649131/bec17905-e5e4-469d-8145-bf74e8157091">

**Comment by aviljakaine** [comment]
Näyttäisi, että tuottajat tallennetaan async:sti (yksi / kutsu) eli jos luo useita tuottajia kerralla niin tallennusjärjestys on se, miten bäkkäri onnistuu nämä kutsut käsittelemään -> tallennusjärjestys menee sekaisin. Ilmeisesti kaikki palautuvat kuitenkin id:n mukaisessa järjestyksessä, eli korjaus voisi olla vain tallentaa nämä synkronoidusti (ts. peräjälkeen). Muitakin vaihtoehtoja on, esim muuttaa endpointtia niin, että tuottajat voi välittää listana tms.
