### ISSUE TITLE
Opinto-ohjaaja-roolin oikeuskorjauksia

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#6953]
Kun henkilö on roolissa opinto-ohjaaja **ja** kurssilla roolissa opettaja:

Voi muokata kurssin asetuksia, mutta ilmoittautumisoikeudet jäävät latautumatta (myös kaikki käyttäjäryhmät) ja tulee ilmoitus: Ilmoittautumisoikeuksien lataus epäonnistui.
KORJAUS: Tässä roolissa olevien kurssien opettajien ei tarvitse päästä säätämään ollenkaan kurssin asetuksia eli tämän voisi korjata siten, etteivät tällaiset opet näe ollenkaan kurssin työkaluissa Kurssin asetuksia.

~~Kurssin keskustelu: tulee kaksi viestiä, joissa molemmissa lukee Response returned an error code.
KORJAUS: Opinto-ohjaajan roolissa ei näe ollenkaan ympäristötason keskustelua, mutta jos hän on kurssin opettajana, pitää päästä kurssin keskusteluun ja tehdä siellä niitä asioita, joita kurssin opettaja voi tehdä. Lisäksi pitää pystyä tilaamaan herätteitä kurssin keskusteluista.~~

~~Kurssin arviointi: Jos ei ole minkään ohjausryhmän ohjaaja ei tule näkyviin yhtään opiskelijaa. Tulee ilmoitus "Ilmoittautumisoikeuksien lataus epäonnistui".
Jos on myös ohjausryhmän ohjaaja, arvioinnissa näkyvät vain ohjausryhmän opiskelijat.
KORJAUS: Pitäisi päästä arvioimaan kaikkia kurssin opiskelijoita riippumatta siitä millä linjalla on ja onko hänen ohjausryhmässään vai ei.~~

**Comment by aviljakaine** [comment]
Siirretty keskusteluihin liittyvä osa omaksi issueksi https://github.com/otavanopisto/muikku/issues/6954

**Comment by aviljakaine** [comment]
Siirretty arviointiin liittyvä osa omaksi issueksi https://github.com/otavanopisto/muikku/issues/6955

**Comment by aviljakaine** [comment]
Tässä olennaisin ongelma liittyy siihen, että oikeudet ovat "positiivisia" eli jos opinto-ohjaajalla on kurssin opettajan oikeus niin tarvitsisi pystyä määrittelemään "negatiivinen" sääntö, jossa muissa kuin opinto-ohjaajan roolissa oleville (esim opettaja) oikeus on ok, mutta opinto-ohjaajan kohdalla ei.
