### ISSUE TITLE
Ympäristötason keskustelun poistaminen

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#6964]
Ympäristötason keskustelualue poistetaan käytöstä.
Kurssikohtaiset keskustelut jätetään käyttöön.

Ympäristötason keskustelualueen käytöstä poistamisessa on huomioitava, että kurssikeskusteluiden herätteiden tilaaminen tarvitaan jatkossakin. Herätteitä on siis pystyttävä tilaamaan jatkossakin ja pyrittävä varmistamaan, etteivät kursseilta tilatut herätteet poistu tässä remontissa.

**Comment by pkukkon** [comment]
Been there, done that.
