### ISSUE TITLE
Ohjaamo: Tehtävien vastaukset haetaan väärin

### ISSUE THREAD

**Issue by petja-laitila** [otavanopisto/muikku#6996]
Kun katsoo oppilaan vastauksia tehtäviin opintohistoriassa, Muikku hakee vastauksia katsovan henkilön (esimerkiksi opettajan) käyttäjälle. Eli yleensä vastaukset näkyvät tyhjänä vaikka oppilas olisi niihin vastannutkin.

**Comment by TeroOtavia** [comment]
Fixed
