### ISSUE TITLE
Kurssin arviointitiedot kurssin etusivulle

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#7001]
Kun opiskelija on suorittanut kurssin, kurssin arviointitiedot voisivat löytyä suoritetun kurssin etusivulta. Tehtäväkohtaiset arvioinnithan löytyvät jo tehtävien yhteydestä.

Kurssin etusivulle siis:

- Kerrotaan, että olet jo suorittanut tämän kurssin
- Päivämäärä:
- Arvosana:
- Kurssin sanallinen arviointi:

Suoritusrekisterissä kurssin suoritustiedot näkyvät näin. Ehkä tyylilaji voisi olla jotain saman suuntaista. Ehkä kurssin nimen tilalla voisi olla jonkinlainen otsikko, kuten "Olet suorittanut tämän kurssin"
![image](https://github.com/otavanopisto/muikku/assets/26649131/dad88c05-c785-4724-b611-27d9c4c70b84)

**Comment by aviljakaine** [comment]
Näyttäisi tulevan `activity`-endpointin mukana `assessmentStates`-kentässä nämä pyydetyt tiedot. Ei siis taida tarvita bäkkäriä.
