### ISSUE TITLE
Huoltaja-rooli: Muikun viestin

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#7015]
Huoltajat voivat hakea ja lähettää Muikku-viestejä henkilökuntajäsenille. Huoltajat voivat hakea ja viestitellä muille henkilökuntarooleille, mutta eivät opinto-ohjaajille. Opinto-ohjaajan roolissa olevat rajataan siis huoltajien näkymän ulkopuolelle.

**Comment by aviljakaine** [comment]
Tämä muutettu samaan pakettiin huoltajaroolin kanssa
