### ISSUE TITLE
Opiskelijalle kurssi-ilmoittautumisesta lähtevä automaattivastaus

### ISSUE THREAD

**Issue by ninakurki** [otavanopisto/muikku#7033]
Mahdollisuus opiskelijalle lähtevään automaattivastaukseen kurssi-ilmoittautumisen yhteydessä. 

Toiveena on **kurssikohtainen** viesti eli tämä mahdollisuus olisi jokaisella kurssilla.

**Kurssin asetuksiin** lisätään mahdollisuus kirjoittaa automaattiviesti kurssille ilmoittautuneille. Kirjoituskentän olisi hyvä olla editorillinen, jotta siihen saa tehdä haluamiaan muotoiluja.

Jos tarvitaan otsikko;
Automaattiset viestit
EN: Automatic response messages

Muuten memo-kentän yhteydessä voisi olla esim. tällainen teksti:
Automaattinen vastausviesti ilmoittautuneelle opiskelijalle
EN: Automatic response message for enrolled students in the course

**Automaattiviestin voi kytkeä päälle ja pois.**

Samalla poistetaan opiskelijoiden mahdollisuus lähettää opettajalle terveisiä ilmoittautumisen yhteydessä (muistiokenttä). Kirjoitetaan tilalle ohjeeksi ottaa yhteyttä kurssin opettajaan, jos tulee kysyttävää. Kirjoitan tämän tekstin myöhemmin.

**Comment by ninakurki** [comment]
Uutena toiveena tuli kysymys, että olisiko mahdollista lähettää eri linjoille erilainen automaattiviesti? Käykää Lankisen kanssa tämä vaikka Discordissa.

**Comment by aviljakaine** [comment]
Kysymyksiä:

1. Onko automaattiviesti pelkkä viestin-viesti vai sähköposti tms?
2. Jos viestinviesti niin viestille tarvitaan lähettäjä - ketä olisi järkevin käyttää lähettäjänä? Voisi käyttää myös opiskelijaa itseään vai otetaanko satunnainen opettaja kurssin opettajista?
3. Kurssin asetuksissa viestille on varmaankin määriteltävissä: a) päällä/pois b) viestin otsikko c) viestin sisältö? (Lähinnä tuo otsikkokysymys siis.)
4. Tämä ilmeisesti koskee vain tilannetta, kun opiskelija ilmoittautuu kurssipoimurin kautta?

**Comment by ninakurki** [comment]
Yritän vastata.

1. On varmasti hyvä, että automaattiviesti jää talteen Muikkuun eli silloin se on Muikku-viesti. Mutta eikö lähteneistä Muikku-viesteistä tule häläri sähköpostiin? Näin voisi tapahtua tässäkin tapauksessa. Siinähän ei taida olla sitä viestin sisältöä, mutta ilmoitetaan, että "sinulle on Muikku-viesti".

2. Suurimmassa osassa kursseja on vain yksi opettaja eli se vois olla se. Mutta entäs sitten tosiaan, jos niitä on useampia. Jotenkin tulee mieleen heti semmonen, että jos on enemmän kuin yksi, se lähettäjän voisi valita sen viestin asetuksista? Ja jos ei ois valittu, ni sit se ois eka ope, joka tulee vastaan. Jos tämä on vaikea toteuttaa, niin sitten mennään sillä, että se on se kurssin ope tai joku niistä, jos niitä on useampi kuin yksi.

3. Kyllä. Voisi olla Otsikko + Sisältö ja se päälle/pois-kytkentä. Mahdollisesti lähettäjän valinta, ks. edellinen kohta, jota ilman pystynemme myös elämään. Mietin tosin, että olisiko otsikossa / sisällössä hyvä olla jotain automaattista sisältöä, kuten kurssin nimi ja linkki kurssin etusivulle? Vähän samaan tapaan kuin jos opiskelija lähettää Muikku-viestin opelle kurssilta:
Viestin otsikko oletuksena: ENA3 Englannin kieli ja kulttuuri luovan ilmaisun välineenä (OPS 2021) --> muokattavissa

Sisällössä:
Viesti kurssilta ENA3 Englannin kieli ja kulttuuri luovan ilmaisun välineenä (OPS 2021)
--> kurssin nimi on linkki
--> tässä tapauksessa viesti voisi alkaa "Automaattinen viesti kurssilta..."

4. Ai hitsi. Sen pallerolistan kautta puolesta ilmoittaminen saisi kyllä laukaista sen automaattisen viestin kyllä. Siitähän opellekin tulee heräte. Sit Pyramuksen kautta poimimisen jättäisin väliin, koska siitä ei tule nytkään mitään herätettä kelleen.

**Comment by ninakurki** [comment]
Vielä yksi uusi lisätoive: opettaja saa herätteen, kun opiskelija ilmoittautuu kurssille Kurssipoimurin kautta ja kun joku ilmoittaa opiskelijan kurssille palleronäkymästä. Saisiko herätteisiin näkymään tiedon, että näihin on vastattu automaattisesti?

**Comment by aviljakaine** [comment]
> Vielä yksi uusi lisätoive: opettaja saa herätteen, kun opiskelija ilmoittautuu kurssille Kurssipoimurin kautta ja kun joku ilmoittaa opiskelijan kurssille palleronäkymästä. Saisiko herätteisiin näkymään tiedon, että näihin on vastattu automaattisesti?

Tämänhän voisi varmaan laittaa tuon poistuvan tekstilaatikon tilalle? Mitkä olisi sopivat tekstit silloin kun viesti on lähetetty ja silloin kun ei?

**Comment by ninakurki** [comment]
Siihen tekstilaatikon tilalle ei tarvitse minusta tulla kuin yhdenlainen teksti ja se on multa vielä kirjoittamatta. Siinä ei tarvitse huomioida automaattivastausta mitenkään. 

Tuo toive liittyy siihen viestiin, joka tulee opettajalle, kun kurssille tupsahtaa uusi opiskelija. Niitä viestejä on kahdenlaisia eli se mikä tulee kun opiskelija muksahtaa kurssille Kurssipoimurin kautta ja se mikä tulee, kun opiskelija ilmoitetaan kurssille sen palleronäkymän kautta. Nämähän kaiketi tulevat jatkossakin tiedoksi opettajalle?

**Comment by aviljakaine** [comment]
Niin siis tarkoitin että kun sen (poistuvan) tekstilaatikon sisältö on aiemmin mennyt opettajalle ilmoittautumisviestin yhteydessä, niin sen sisällön tilalle voinee laittaa jonkin tekstin sen automaattisen viestin lähetyksestä.

Laitoin siihen alustavasti tämmöiset (ensimmäinen silloin, kun viesti lähetetty, jälkimmäinen jos ei)
```
Opiskelijalle on lähetetty automaattinen liittymisviesti
Opiskelijalle ei lähetetty automaattista liittymisviestiä
```
Fronttiheput voivat varmaan riipiä sen kentän pois ja laittaa tilalle tekstin kun se on valmis.

**Comment by aviljakaine** [comment]
Vielä ainakin yksi kysymys; mites tuon ohjaamon viestilaatikon kanssa, otetaanko sekin pois samoin kuin opiskelijan ilmoittautumisessa, vai käsitelläänkö se jotenkin eri tavalla kun ohjaaja täyttää sen?
