### ISSUE TITLE
Automaattinen lomaviesti lähtee liian aikaisin

### ISSUE THREAD

**Issue by saaralepisto** [otavanopisto/muikku#7100]
Automaattisten lomaviestien päivämäärät (sekä, alku, että loppupäivämäärä) tallennetaan yhtä päivää aiemmaksi, kuin mitä käyttöliittymässä asetetaan. Vika paikantuu fronttiin, sillä jo siellä bäkkärille annettavassa payloadissa on väärät päivämäärät.

https://helpdesk.muikkuverkko.fi/scp/tickets.php?id=4901
https://helpdesk.muikkuverkko.fi/scp/tickets.php?id=4942

**Comment by TeroOtavia** [comment]
Frontista viesti lähtee Iso formaatissa bäkkärille. Näin on tapahtunut ties kuinka kauan. Toki jos bäkkäri on muuttunat Date käsittelyään ominaisuuden teon yhteydessä niin siinä tapauksessa muutetaan frontista myös lähtemään ilman formatointia.
