### ISSUE TITLE
Yhdistelytehtävässä laatikkoparit, ei "kengännauhoja"

### ISSUE THREAD

**Issue by anttileppa** [otavanopisto/muikku#713]
_From @ilmoeuro on January 16, 2015 9:6_

Opiskelijana haluaisin että yhdistelytehtävissä voin raahata oikeat vastaukset paikoilleen. 

Yhdistelytehtävä muodostuu kahdesta sarakkeesta. Molemien sarakkeiden vaihtoehtojen järjestys on sattumanvarainen.  Katso issue 498

Sarakkeessa A olevat vaihtoehdot pysyvät paikoillaan. 
Sarakkeessa B olevat vaihtoehdot ovat raahattavissa. 

Tilaajan yhteyshenkilö Nina K. 
(story edit by Tommi, ei Ilmo)

_Copied from original issue: otavanopisto/board#495_

**Comment by ninakurki** [comment]
Done
