### ISSUE TITLE
Ympäristön etusivu - Viestien päivittyminen

### ISSUE THREAD

**Issue by anttileppa** [otavanopisto/muikku#724]
_From @anttileppa on February 9, 2015 4:20_

Käyttäjänä haluaisin, että etusivun viestit päivittyisivät reaaliaikaisesti myös ympäristön etusivulle.

_Copied from original issue: otavanopisto/board#542_

**Comment by anttiviljakainen** [comment]
New Communicator messages do pop up live on the front page when you receive one. Deprecated or different issue?
