### ISSUE TITLE
ckeditor image. This type url is not working

### ISSUE THREAD

**Issue by jarkkoh** [otavanopisto/muikku#831]
This type url is not working:
https://fi.wiktionary.org/wiki/%C3%84#/media/File:Sv-cursive-capital-letter-%C3%84.jpg

![invalid_url](https://cloud.githubusercontent.com/assets/3033999/10818397/e90cf79a-7e49-11e5-83ef-b56f5357cbcc.gif)

**Comment by pkukkon** [comment]
The URL is not an image but a HTML document. The URL of the image shown on that particular page is https://upload.wikimedia.org/wikipedia/commons/0/0a/Sv-cursive-capital-letter-%C3%84.jpg which, in turn, displays correctly.
