### ISSUE TITLE
Discussion, load more messages button loads one message by time

### ISSUE THREAD

**Issue by jarkkoh** [otavanopisto/muikku#872]
Long thread, load more button loads only one message.
![load_more_messages](https://cloud.githubusercontent.com/assets/3033999/10946602/cd326672-832b-11e5-9581-3ebd90ff800d.gif)

**Comment by avukkonen** [comment]
How long a thread?

**Comment by avukkonen** [comment]
At this time, with 31 messages in a thread, I was unable to repeat it.

**Comment by jarkkoh** [comment]
There was problem, but unable to repeat anymore.
