### ISSUE TITLE
Workspace not showing in evaluation 

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#874]
Workspace: 

https://otavanopisto.muikkuverkko.fi/workspace/biisinteko

The list in the evaluation view is not made with rest & dust. It's magically magic jsf.

<img width="340" alt="screen shot 2015-11-05 at 12 36 52" src="https://cloud.githubusercontent.com/assets/3994573/10966148/584d3460-83ba-11e5-8295-b68d8bd4e5d1.png">
<img width="587" alt="screen shot 2015-11-05 at 12 37 59" src="https://cloud.githubusercontent.com/assets/3994573/10966147/57793f98-83ba-11e5-8289-fd4c598ce90a.png">

**Comment by anttileppa** [comment]
The course did not have a course number and subject and the view has weird limitation that both are required, this requirement will be removed in #508
