### ISSUE TITLE
Discussion, after thread removal view is not updating

### ISSUE THREAD

**Issue by jarkkoh** [otavanopisto/muikku#942]
![thread_view_update](https://cloud.githubusercontent.com/assets/3033999/11239596/ac5f3f0e-8df5-11e5-87cf-d58e28c2a5a1.jpg)

**Comment by avukkonen** [comment]
What browser. For me it works in firefox.

**Comment by avukkonen** [comment]
This seems to be a mApi caching issue.

**Comment by issakainen** [comment]
Old issue, check if still valid.

**Comment by jarkkoh** [comment]
It's fixed.
