### ISSUE TITLE
Discussion. Selected area messages in wrong order, shows 4 messages default.

### ISSUE THREAD

**Issue by jarkkoh** [otavanopisto/muikku#943]
IE11, staging

After message area selection, there is only 4 messages in wrong order. Clicking load more messages opens all messages, but order is still wrong. Issue fixed in 15 minutes and now area selection shows more than 4 area messages in correct order.
However, when I click load more messages there is message that belongs to other area.
![discussion_area_selection](https://cloud.githubusercontent.com/assets/3033999/11240242/cb18ee6e-8df9-11e5-90f8-19992c80dc26.gif)
![message_wrong_area](https://cloud.githubusercontent.com/assets/3033999/11240289/308dac8a-8dfa-11e5-963a-c53899ee6090.gif)

**Comment by issakainen** [comment]
Old issue, check if still valid.

**Comment by jarkkoh** [comment]
It's fixed.
