### ISSUE TITLE
Discussion, new message containing ?? causes parse error

### ISSUE THREAD

**Issue by jarkkoh** [otavanopisto/muikku#945]
https://muikku.staging.fi/discussion#thread/1/191

![parse_error](https://cloud.githubusercontent.com/assets/3033999/11240715/8aa28ddc-8dfd-11e5-9a76-2b2bd4e758d8.gif)

**Comment by ilmoeuro** [comment]
This will solve the problem:

http://stackoverflow.com/a/17660503
