### ISSUE TITLE
Evaluation does not work well for Pekka Niemi

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#989]
![nayttokuva 2015-11-26 kello 13 12 38](https://cloud.githubusercontent.com/assets/3994573/11422937/d03417b6-9448-11e5-94cf-fd045e7b7be8.png)

>Ensinnäkin. Minulla on vaikeuksia päästä sisään arviointiosioon. Omalla mac -koneella en pääse arviointiin. Safarilla pääsen yleensä lukemaan ja arvioimaan tehtäviä, mutta arviointi ei onnistu. Firefox ja Chrome eivät päästä macillä ollenkaan sisään. Herjaa erilaisia virheitä.

>PC-lllä pääsin arvioimaan, mutta loppuarvosanan antaminen ei onnistu. Herjaa: error.

>Aleksi Hänninen yritti pyytää arviointia YH1 -kurssista, mutta hänelle tuli error ja hän lähetti pyynnön sähköpostilla - tuota en siis pystynyt arvioimaan loppuun. Lisäksi en tiedä onko hän lukiolainen vai internetix -opiskelija.

>Toisen opiskeijan arviontipyyntö on tullut normaalista M3-kautta.

>ps. Vanha muikku toimii ilahduttavan hyvin.

Kun tiedustelin hänen nettiyhteyttään:

> Yhteys on langaton 4G.

Opettajan nimi on Pekka Niemi

**Comment by avukkonen** [comment]
I promised the teacher he would be contacted when this is addressed.

**Comment by avukkonen** [comment]
Ticket no. #901568

**Comment by jjlankinen** [comment]
Pekka has been contacted again and informed about coming updates regarding evaluation views's problems.
