### ISSUE TITLE
Errors on evaluation load

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#994]
![evaluation_image](https://cloud.githubusercontent.com/assets/3994573/11435749/9217774a-94e6-11e5-9d30-ff57b51de2d5.png)

> ** 26.11.2015 3:49 Erroreita pukkaa Kai Kaskela **
Arviointi toimii kyllä kuitenkin (hitaasti), iski vaan tommosen näkyville aluksi.

**Comment by avukkonen** [comment]
Ticket no #340707

**Comment by jjlankinen** [comment]
Seems to be fixed by Muikku build from 4.12.
