### ISSUE TITLE
Assignment's titles differs in evaluation

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#998]
In evaluation view there are different assignment titles presented to teachers in grid view and in evaluation modal.

**Comment by pkukkon** [comment]
Evaluation grid uses workspace material titles (correct) whereas evaluation modals use material titles (incorrect).

Might be enough to change evaluation.js and its loadHtmls method where title is taken via htmlMaterialMap when it could be taken straight from workspace material?
